### ISSUE TITLE
Celery Scheduler Traceback in Logs

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1071]
**Describe the bug**
It looks like an issue with prometheus metrics in CI. On inspection of the logs, I saw this traceback

```
  | celery beat v4.3.0 (rhubarb) is starting.
-- | --
  | __    -    ... __   -        _
  | LocalTime -> 2019-08-28 20:43:10
  | Configuration ->
  | . broker -> amqp://guest:**@rabbitmq.hccm-ci.svc.cluster.local:5672//
  | . loader -> celery.loaders.app.AppLoader
  | . scheduler -> celery.beat.PersistentScheduler
  | . db -> celerybeat-schedule
  | . logfile -> [stderr]@%INFO
  | . maxinterval -> 5.00 minutes (300s)
  | [2019-08-28 20:43:10,132: INFO/MainProcess] beat: Starting...
  | [2019-08-28 23:45:42,517: WARNING/MainProcess] Exception in thread Thread-1:
  | Traceback (most recent call last):
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
  | self.run()
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 864, in run
  | self._target(*self._args, **self._kwargs)
  | File "/opt/app-root/src/koku/api/apps.py", line 35, in _collect_db_metrics
  | _collect_db_metrics()
  | File "/opt/app-root/src/koku/api/apps.py", line 35, in _collect_db_metrics
  | _collect_db_metrics()
  | File "/opt/app-root/src/koku/api/apps.py", line 35, in _collect_db_metrics
  | _collect_db_metrics()
  | [Previous line repeated 87 more times]
  | File "/opt/app-root/src/koku/api/apps.py", line 33, in _collect_db_metrics
  | DBSTATUS.collect()
  | File "/opt/app-root/src/koku/koku/metrics.py", line 87, in collect
  | PGSQL_GAUGE.labels(schema=item.get('schema')).set(item.get('size', 0))
  | File "/opt/app-root/lib/python3.6/site-packages/prometheus_client/metrics.py", line 344, in set
  | self._value.set(float(value))
  | TypeError: float() argument must be a string or a number, not 'NoneType'
  | [2019-08-29 04:00:00,114: INFO/MainProcess] Scheduler: Sending due task celery.backend_cleanup (celery.backend_cleanup)
```

**Comment by chambridge** [comment]
Should this code be running on the scheduler?

**Comment by adberglund** [comment]
I think not.

**Comment by lcouzens** [comment]
Not easily reproducible however if it appears again sentry should catch this now.
