### ISSUE TITLE
OpenShift Provider Creation Fails

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1124]
**Describe the bug**
Duplicate "blank" billing_source records are getting created for OpenShift providers, when only a single shared row should be used for that field. This is causing provider creation to fail. Adding validation for the new fields on providers prevents this.

## Traceback

```
[2019-09-10 10:00:31,990] INFO: API: /api/cost-management/v1/providers/ -- ACCOUNT: 6089719 USER: insights-qa
[2019-09-10 10:00:32,030] INFO: Stub to verify that OCP report for cluster yoooo is accessible.
[2019-09-10 10:00:32,034] ERROR: Internal Server Error: /api/cost-management/v1/providers/
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 468, in raise_uncaught_exception
    raise exc
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/app-root/src/koku/api/provider/view.py", line 217, in create
    return super().create(request=request, args=args, kwargs=kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/serializers.py", line 213, in save
    self.instance = self.create(validated_data)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/app-root/src/koku/api/provider/serializers.py", line 145, in create
    bill, __ = ProviderBillingSource.objects.get_or_create(**billing_source)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 412, in get
    (self.model._meta.object_name, num)
api.provider.models.ProviderBillingSource.MultipleObjectsReturned: get() returned more than one ProviderBillingSource -- it returned 11!
```

**Comment by dchorvat1** [comment]
verified
