### ISSUE TITLE
OpenShift builds failing on install of googleapis-common-protos==1.6.0

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1149]
**Describe the bug**
OpenShift builds are failing trying to install googleapis-common-protos==1.6.0

**To Reproduce**
1. Trigger koku build in OpenShift

**Traceback**

```
An error occurred while installing googleapis-common-protos==1.6.0 --hash=sha256:e61b8ed5e36b976b487c6e7b15f31bb10c7a0ca7bd5c0e837f4afab64b53a0c6! Will try again.
--
  | Installing initially failed dependencies…
  | [pipenv.exceptions.InstallError]:   File "/opt/app-root/src/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/core.py", line 1874, in do_install
  | [pipenv.exceptions.InstallError]:       keep_outdated=keep_outdated
  | [pipenv.exceptions.InstallError]:   File "/opt/app-root/src/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/core.py", line 1253, in do_init
  | [pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
  | [pipenv.exceptions.InstallError]:   File "/opt/app-root/src/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/core.py", line 859, in do_install_dependencies
  | [pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
  | [pipenv.exceptions.InstallError]:   File "/opt/app-root/src/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/core.py", line 763, in batch_install
  | [pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
  | [pipenv.exceptions.InstallError]:   File "/opt/app-root/src/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/core.py", line 681, in _cleanup_procs
  | [pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
  | [pipenv.exceptions.InstallError]: ['Collecting googleapis-common-protos==1.6.0 (from -r /tmp/pipenv-csmdvisl-requirements/pipenv-fi10epzh-requirement.txt (line 1))', '  Using cached https://files.pythonhosted.org/packages/eb/ee/e59e74ecac678a14d6abefb9054f0bbcb318a6452a30df3776f133886d7d/googleapis-common-protos-1.6.0.tar.gz' , '    Complete output from command python setup.py egg_info:', '    Traceback (most recent call last):', '      File "<string>", line 1, in <module>', '      File "/opt/app-root/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>', '        from setuptools.extern.six.moves import filter, filterfalse, map', '      File "/opt/app-root/lib/python3.6/site-packages/setuptools/extern/__init__.py", line 1, in <module>', '        from pkg_resources.extern import VendorImporter', '      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>', '        @_call_aside', '      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside', '        f(*args, **kwargs)', '      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3045, in _initialize_master_working_set', '        dist.activate(replace=False)', '      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2577, in activate', '        declare_namespace(pkg)', '      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2151, in declare_namespace', '        _handle_ns(packageName, path_item)', '      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2091, in _handle_ns', '        _rebuild_mod_path(path, packageName, module)', '      File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2120, in _rebuild_mod_path', '        orig_path.sort(key=position_in_sys_path)', "    AttributeError: '_NamespacePath' object has no attribute 'sort'", '    ', '    ----------------------------------------']
  | [pipenv.exceptions.InstallError]: ['Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0nl5g7ff/googleapis-common-protos/']
  | ERROR: ERROR: Package installation failed...
```

**Comment by infinitewarp** [comment]
With the commit referenced here and an additional commit from @adberglund at https://github.com/RedHatInsights/e2e-deploy/pull/690, it looks like this issue is resolved.

I'll leave this issue open until we verify seeing the new builds in the various OSD projects.

**Comment by dchorvat1** [comment]
verified
