### ISSUE TITLE
Posting OCP provider without billing_source returns 500

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#1168]
**Describe the bug**
The api returns 500 when posting OCP provider without `billing_source` field in the json.

**To Reproduce**
1. Go to `/providers/`
2. POST
```
{
    "name": "OCP-test",
    "type": "OCP",
    "authentication": {
        "provider_resource_name": "OCP-test"
    }
}
``` 
3. See error

**Expected behavior**
201 (posting providers like this was working until encountering this)

**Traceback**
```
[2019-09-26 08:57:05,488] ERROR: Internal Server Error: /api/cost-management/v1/providers/
--
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
  | response = get_response(request)
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
  | response = self.process_exception_by_middleware(e, request)
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
  | response = wrapped_callback(request, *callback_args, **callback_kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
  | return view_func(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
  | return self.dispatch(request, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
  | response = self.handle_exception(exc)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
  | self.raise_uncaught_exception(exc)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
  | raise exc
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
  | response = handler(request, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
  | response = view_func(request, *args, **kwargs)
  | File "/opt/app-root/src/koku/api/provider/view.py", line 122, in create
  | return super().create(request=request, args=args, kwargs=kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/mixins.py", line 19, in create
  | self.perform_create(serializer)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/mixins.py", line 24, in perform_create
  | serializer.save()
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/serializers.py", line 213, in save
  | self.instance = self.create(validated_data)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 52, in inner
  | return func(*args, **kwds)
  | File "/opt/app-root/src/koku/api/provider/serializers.py", line 160, in create
  | bill, __ = ProviderBillingSource.objects.get_or_create(**billing_source)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
  | return getattr(self.get_queryset(), name)(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 538, in get_or_create
  | return self.get(**kwargs), False
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 412, in get
  | (self.model._meta.object_name, num)
  | api.provider.models.ProviderBillingSource.MultipleObjectsReturned: get() returned more than one ProviderBillingSource -- it returned 2!
  | 10.130.5.157 - - [26/Sep/2019:08:57:05 +0000] "POST /api/cost-management/v1/providers/ HTTP/1.1" 500 27 "https://ci.cloud.redhat.com/api/cost-management/v1/providers/ " "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36"
```

**Additional context**
Tested on CI

**Comment by adberglund** [comment]
@blentz Are you looking into this with the Azure bug fix as well?

**Comment by dchorvat1** [comment]
this is a duplicate of #1124
