### ISSUE TITLE
Adding non-OCP provider with markup _and_ rates raises 500

### ISSUE THREAD

**Issue by maskarb** [project-koku/koku#1178]
**Describe the bug**
Adding non-OCP provider with markup _and_ rates should return 400 with "not a valid source", but raises 500 instead.

**To Reproduce**
1. Add non-OCP cost-model with rates and markup:
```
{
    "name": "Test Cost Model",
    "description": "test",
    "source_type": "AWS",
    "provider_uuids": [],
    "rates": [
        {"metric": {"name": "cpu_core_request_per_hour"},
        "tiered_rates": [{"unit": "USD", "value": 0.10}]
        }
    ],
    "markup": {
        "value": 10,
        "unit": "percent"
    }
}
```

2. See error

```koku_server       | [2019-09-30 13:30:47,103] ERROR: Internal Server Error: /api/cost-management/v1/costmodels/
koku_server       | Traceback (most recent call last):
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
koku_server       |     response = get_response(request)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
koku_server       |     response = self.process_exception_by_middleware(e, request)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
koku_server       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
koku_server       |     return view_func(*args, **kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
koku_server       |     return self.dispatch(request, *args, **kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
koku_server       |     response = self.handle_exception(exc)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
koku_server       |     self.raise_uncaught_exception(exc)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
koku_server       |     raise exc
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
koku_server       |     response = handler(request, *args, **kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
koku_server       |     response = view_func(request, *args, **kwargs)
koku_server       |   File "/koku/koku/cost_models/view.py", line 149, in create
koku_server       |     return super().create(request=request, args=args, kwargs=kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/mixins.py", line 20, in create
koku_server       |     headers = self.get_success_headers(serializer.data)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/serializers.py", line 559, in data
koku_server       |     ret = super().data
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/serializers.py", line 261, in data
koku_server       |     self._data = self.to_representation(self.instance)
koku_server       |   File "/koku/koku/cost_models/serializers.py", line 373, in to_representation
koku_server       |     'label_metric': display_data.label_metric,
koku_server       | AttributeError: 'NoneType' object has no attribute 'label_metric'
koku_server       | [2019-09-30 13:30:47,108] ERROR: "POST /api/cost-management/v1/costmodels/ HTTP/1.1" 500 134735
```

**Expected behavior**
Adding non-OCP costmodel with rates and markup should return 400 with "not a valid source"

**Comment by maskarb** [comment]
for QA

**Comment by dchorvat1** [comment]
Verified, 3f58b1de9620fdc8e3e106f3fbe9f9b068c86d21
