### ISSUE TITLE
Sources Service not waiting for migrations to run in OpenShift deployments

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#1203]
In our e2e OpenShift deployments the Sources client is not waiting for migrations to run when deploying.  One example that illustrates this was with a recent change to the model.

Restarting the pod once the Koku-server was up and running resolved the issue but something should be done in the jenkins/e2e workflow to ensure migrations are ran before Sources Client (and possibly other services) deploys
```
---> Serving application with gunicorn (koku.wsgi) ...
[2019-10-02 18:48:13 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2019-10-02 18:48:13 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080  (1)
[2019-10-02 18:48:13 +0000] [1] [INFO] Using worker: threads
[2019-10-02 18:48:13 +0000] [37] [INFO] Booting worker with pid: 37
[2019-10-02 18:48:13 +0000] [38] [INFO] Booting worker with pid: 38
[2019-10-02 18:48:24,934] INFO: Listening for kafka events
10.131.0.1 - - [02/Oct/2019:18:48:25 +0000] "GET /api/cost-management/v1/status/?liveness HTTP/1.1" 200 14 "-" "kube-probe/1.11+"
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column api_sources.endpoint_id does not exist
LINE 1: ...i_sources"."auth_header", "api_sources"."offset", "api_sourc...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app-root/src/koku/sources/kafka_listener.py", line 441, in asyncio_sources_thread
    load_process_queue()
  File "/opt/app-root/src/koku/sources/kafka_listener.py", line 91, in load_process_queue
    pending_events = _collect_pending_items()
  File "/opt/app-root/src/koku/sources/kafka_listener.py", line 70, in _collect_pending_items
    create_events = storage.load_providers_to_create()
  File "/opt/app-root/src/koku/sources/storage.py", line 91, in load_providers_to_create
    for provider in all_providers:
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column api_sources.endpoint_id does not exist
LINE 1: ...i_sources"."auth_header", "api_sources"."offset", "api_sourc...
                                                             ^


[2019-10-02 18:48:29,521] INFO: Listening for kafka events
10.131.0.1 - - [02/Oct/2019:18:48:29 +0000] "GET /api/cost-management/v1/status/ HTTP/1.1" 200 3437 "-" "kube-probe/1.11+"
10.131.0.1 - - [02/Oct/2019:18:48:34 +0000] "GET /api/cost-management/v1/status/?liveness HTTP/1.1" 200 14 "-" "kube-probe/1.11+"
[2019-10-02 18:48:38,272] INFO: Listener started.  Waiting for messages...
[2019-10-02 18:48:38,273] INFO: Waiting to process incoming kafka messages...
[2019-10-02 18:48:38,273] INFO: Processing koku provider events...
Unclosed AIOKafkaConsumer
consumer: <aiokafka.consumer.consumer.AIOKafkaConsumer object at 0x7fcc340dd908>
10.131.0.1 - - [02/Oct/2019:18:48:39 +0000] "GET /api/cost-management/v1/status/ HTTP/1.1" 200 3437 "-" "kube-probe/1.11+"
10.131.0.1 - - [02/Oct/2019:18:48:44 +0000] "GET /api/cost-management/v1/status/?liveness HTTP/1.1" 200 14 "-" "kube-probe/1.11+"
10.131.0.1 - - [02/Oct/2019:18:48:49 +0000] "GET /api/cost-management/v1/status/ HTTP/1.1" 200 3437 "-" "kube-probe/1.11+"
10.131.0.1 - - [02/Oct/2019:18:48:54 +0000] "GET /api/cost-management/v1/status/?liveness HTTP/1.1" 200 14 "-" "kube-probe/1.11+"
10.131.0.1 - - [02/Oct/2019:18:48:59 +0000] "GET /api/cost-management/v1/status/ HTTP/1.1" 200 3437 "-" "kube-probe/1.11+"
10.131.0.1 - - [02/Oct/2019:18:49:04 +0000] "GET /api/cost-management/v1/status/?liveness HTTP/1.1" 200 14 "-" "kube-probe/1.11+"
```

**Comment by dccurtis** [comment]
Problem was addressed with #2031
