### ISSUE TITLE
Create AWS/OCP without provider_resource_name or bucket raises 500

### ISSUE THREAD

**Issue by maskarb** [project-koku/koku#1226]
**Describe the bug**
Creating AWS/OCP provider without provider_resource_name or bucket raises 500.

**To Reproduce**
1. Create OCP or AWS provider without provider_resource_name
```{
    "name": "provider",
    "type": "AWS",
    "authentication": {
        "provider_resource_name": ""
    },
    "billing_source": {
        "bucket": ""
    }
}
```
2. See error
```
koku_server       | [2019-10-09 13:37:29,471] ERROR: Internal Server Error: /api/cost-management/v1/providers/
koku_server       | Traceback (most recent call last):
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
koku_server       |     response = get_response(request)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
koku_server       |     response = self.process_exception_by_middleware(e, request)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
koku_server       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
koku_server       |     return view_func(*args, **kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
koku_server       |     return self.dispatch(request, *args, **kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
koku_server       |     response = self.handle_exception(exc)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
koku_server       |     self.raise_uncaught_exception(exc)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
koku_server       |     raise exc
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
koku_server       |     response = handler(request, *args, **kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
koku_server       |     response = view_func(request, *args, **kwargs)
koku_server       |   File "/koku/koku/api/provider/view.py", line 132, in create
koku_server       |     return super().create(request=request, args=args, kwargs=kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/mixins.py", line 18, in create
koku_server       |     serializer.is_valid(raise_exception=True)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/serializers.py", line 235, in is_valid
koku_server       |     self._validated_data = self.run_validation(self.initial_data)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/serializers.py", line 430, in run_validation
koku_server       |     value = self.to_internal_value(data)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/serializers.py", line 487, in to_internal_value
koku_server       |     validated_value = field.run_validation(primitive_value)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/serializers.py", line 433, in run_validation
koku_server       |     value = self.validate(value)
koku_server       |   File "/koku/koku/api/provider/serializers.py", line 70, in validate
koku_server       |     if data.get('credentials').get('provider_resource_name'):
koku_server       | AttributeError: 'NoneType' object has no attribute 'get'
koku_server       | [2019-10-09 13:37:29,475] ERROR: "POST /api/cost-management/v1/providers/ HTTP/1.1" 500 145407
```
**Expected behavior**
Creating provider with missing params should raise 400 Bad Request

**Comment by lcouzens** [comment]
Verified
