### ISSUE TITLE
Api blows up when incorrectly adding local-gcp provider

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#1299]
**Describe the bug**
Api blows up when incorrectly adding local-gcp provider

**To Reproduce**
1. Go to '/api/cost-management/v1/providers/'
2. Add gcp-local provider but only fill out name filed and type
3. See error

**Expected behavior**
Api returns correct error message with required fields etc.

**Context (please complete the following information):**
 - OS: fedora
 - Browser: firefox
 - Commit Hash from status endpoint: 96a12fc0e55ee08d444f5919b549ec575683a988

**Additional context**
```
koku_server       | [2019-10-23 13:29:45,240] INFO: API: /api/cost-management/v1/providers/ -- ACCOUNT: 10001 USER: user_dev
koku_server       | [2019-10-23 13:29:45,311] ERROR: Internal Server Error: /api/cost-management/v1/providers/
koku_server       | Traceback (most recent call last):
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
koku_server       |     response = get_response(request)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
koku_server       |     response = self.process_exception_by_middleware(e, request)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
koku_server       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
koku_server       |     return view_func(*args, **kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
koku_server       |     return self.dispatch(request, *args, **kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
koku_server       |     response = self.handle_exception(exc)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
koku_server       |     self.raise_uncaught_exception(exc)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
koku_server       |     raise exc
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
koku_server       |     response = handler(request, *args, **kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
koku_server       |     response = view_func(request, *args, **kwargs)
koku_server       |   File "/koku/koku/api/provider/view.py", line 132, in create
koku_server       |     return super().create(request=request, args=args, kwargs=kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/mixins.py", line 17, in create
koku_server       |     serializer = self.get_serializer(data=request.data)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/generics.py", line 110, in get_serializer
koku_server       |     return serializer_class(*args, **kwargs)
koku_server       |   File "/koku/koku/api/provider/serializers.py", line 241, in __init__
koku_server       |     self.fields['authentication'] = AUTHENTICATION_SERIALIZERS.get(provider_type)()
koku_server       | TypeError: 'NoneType' object is not callable
koku_server       | [2019-10-23 13:29:45,312] ERROR: "POST /api/cost-management/v1/providers/ HTTP/1.1" 500 128098
```

**Comment by lcouzens** [comment]
Raising priority on this as it seems we have similar issues when add a standard GCP provider with bad creds.

```sources_client    | [2019-10-23 16:17:09,791] ERROR: Kafka Connection Failure: ('Unable to connect to kafka server. Reason: ', "ConnectionError: Unable to bootstrap from [('kafka', 29092, <AddressFamily.AF_UNSPEC: 0>)]"). Reconnecting...
koku_server       | [2019-10-23 16:17:12,970] ERROR: Internal Server Error: /api/cost-management/v1/providers/
koku_server       | Traceback (most recent call last):
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
koku_server       |     response = get_response(request)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
koku_server       |     response = self.process_exception_by_middleware(e, request)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
koku_server       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
koku_server       |     return view_func(*args, **kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
koku_server       |     return self.dispatch(request, *args, **kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
koku_server       |     response = self.handle_exception(exc)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
koku_server       |     self.raise_uncaught_exception(exc)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
koku_server       |     raise exc
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
koku_server       |     response = handler(request, *args, **kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
koku_server       |     response = view_func(request, *args, **kwargs)
koku_server       |   File "/koku/koku/api/provider/view.py", line 132, in create
koku_server       |     return super().create(request=request, args=args, kwargs=kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/mixins.py", line 19, in create
koku_server       |     self.perform_create(serializer)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/mixins.py", line 24, in perform_create
koku_server       |     serializer.save()
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/serializers.py", line 213, in save
koku_server       |     self.instance = self.create(validated_data)
koku_server       |   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 52, in inner
koku_server       |     return func(*args, **kwds)
koku_server       |   File "/koku/koku/api/provider/serializers.py", line 286, in create
koku_server       |     interface.cost_usage_source_ready(credentials, data_source)
koku_server       |   File "/koku/koku/providers/provider_access.py", line 104, in cost_usage_source_ready
koku_server       |     return self.service.cost_usage_source_is_reachable(credential, source_name)
koku_server       |   File "/koku/koku/providers/gcp/provider.py", line 29, in cost_usage_source_is_reachable
koku_server       |     storage_client = storage.Client()
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/google/cloud/storage/client.py", line 95, in __init__
koku_server       |     project=project, credentials=credentials, _http=_http
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/google/cloud/client.py", line 226, in __init__
koku_server       |     _ClientProjectMixin.__init__(self, project=project)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/google/cloud/client.py", line 178, in __init__
koku_server       |     project = self._determine_default(project)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/google/cloud/client.py", line 193, in _determine_default
koku_server       |     return _determine_default_project(project)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/google/cloud/_helpers.py", line 186, in _determine_default_project
koku_server       |     _, project = google.auth.default()
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/google/auth/_default.py", line 317, in default
koku_server       |     raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
koku_server       | google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
koku_server       | [2019-10-23 16:17:12,972] ERROR: "POST /api/cost-management/v1/providers/ HTTP/1.1" 500 177756```

**Comment by infinitewarp** [comment]
@adberglund suggests we also ensure we have good and updated developer documentation so we know to set up our GCP service account and credentials appropriately.

**Comment by katherine-black** [comment]
First part of this was fixed via https://github.com/project-koku/koku/pull/1301
The missing credentials were addressed by @werwty

**Comment by werwty** [comment]
Can confirm that the CI environment has the keys loaded in correctly.

```
bash-4.4$  http -a jalberts@redhat.com POST https://ci.cloud.redhat.com/api/cost-management/v1/providers/ name="GCP Provider" type=GCP billing_source:='{"data_source": {"bucket": "koku-billing-bucket",  "report_prefix": "koku-billing"}}' authentication:='{"credentials": {"project_id": "gcp_project_id"}}'
http: password for jalberts@redhat.com@ci.cloud.redhat.com: 
HTTP/1.1 201 Created
Transfer-Encoding: chunked
X-Powered-By: Express
allow: GET, POST, HEAD, OPTIONS
cache-control: max-age=0, no-cache, no-store, must-revalidate
connection: keep-alive
content-type: application/json
date: Thu, 31 Oct 2019 19:06:53 GMT
expires: Thu, 31 Oct 2019 19:06:53 GMT
server: openresty/1.13.6.1
set-cookie: bd2e829019cc5851647126f4f0834941=cbfcbf9d74fe080e13cc044ccf2fe78f; path=/; HttpOnly; Secure
vary: Accept, Origin
x-content-type-options: nosniff
x-fakamai-app-hint: API
x-fakamai-downstream-host: https://api-gateway-ci.5a9f.insights-dev.openshiftapps.com
x-fakamai-env: ci
x-frame-options: SAMEORIGIN
x-rh-insights-request-id: 660f2e8c0fd544139c9aa0328e7375a3

{
    "authentication": {
        "credentials": {
            "project_id": "gcp_project_id"
        },
        "provider_resource_name": null,
        "uuid": "ba7dc725-3556-4c77-aad1-5bc7a9184147"
    },
    "billing_source": {
        "bucket": null,
        "data_source": {
            "bucket": "koku-billing-bucket",
            "report_prefix": "koku-billing"
        },
        "uuid": "1916d8a5-aa60-4338-a168-f5f23889e327"
    },
    "created_by": {
        "email": "jalberts+qa@redhat.com",
        "username": "jalberts@redhat.com",
        "uuid": "b74eac0b-9f39-4848-96dc-2118b802db0d"
    },
    "created_timestamp": "2019-10-31T19:06:53.843910Z",
    "customer": {
        "account_id": "1460290",
        "date_created": "2018-10-22T18:56:45.647027Z",
        "uuid": "b2b41ac5-3850-499d-9290-ad6eed7408d1"
    },
    "name": "GCP Provider",
    "type": "GCP",
    "uuid": "3e64149f-a02c-4f77-bff0-afd51fe0b4a8"
}
```

**Comment by lcouzens** [comment]
Verified
Commit: a1976d66754f83ac83790fd827c29892b583627f
