### ISSUE TITLE
Providers 500 error on existing provider resource name

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1400]
**Describe the bug**
We get an undefined error from the cost management sources page or 500 screen when creating a provider via the API when the provider resource name is already used elsewhere

**To Reproduce**
1. Create a provider
2. Create a 2nd provider and use the same provider resource name

**Expected behavior**
We should have a defined 400-level error and helpful message returned indicating the field can't be reused.

 Or... we should allow reuse? This is likely only an issue for us as internal users sharing an account. For now, let's not allow.

**Traceback**
```

[2019-11-13 19:15:45,908] ERROR: Internal Server Error: /api/cost-management/v1/providers/
--
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 538, in get_or_create
  | return self.get(**kwargs), False
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
  | self.model._meta.object_name
  | api.provider.models.ProviderAuthentication.DoesNotExist: ProviderAuthentication matching query does not exist.
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
  | return self.cursor.execute(sql, params)
  | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "api_providerauthentication_provider_resource_name_key"
  | DETAIL:  Key (provider_resource_name)=(549fc82c-6d7b-44bd-8e5e-f4931aca91b1) already exists.
  |  
  |  
  | The above exception was the direct cause of the following exception:
  |  
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
  | response = get_response(request)
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
  | response = self.process_exception_by_middleware(e, request)
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
  | response = wrapped_callback(request, *callback_args, **callback_kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
  | return view_func(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
  | return self.dispatch(request, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
  | response = self.handle_exception(exc)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
  | self.raise_uncaught_exception(exc)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
  | raise exc
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
  | response = handler(request, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
  | response = view_func(request, *args, **kwargs)
  | File "/opt/app-root/src/koku/api/provider/view.py", line 132, in create
  | return super().create(request=request, args=args, kwargs=kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/mixins.py", line 19, in create
  | self.perform_create(serializer)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/mixins.py", line 24, in perform_create
  | serializer.save()
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/serializers.py", line 213, in save
  | self.instance = self.create(validated_data)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 52, in inner
  | return func(*args, **kwds)
  | File "/opt/app-root/src/koku/api/provider/serializers.py", line 294, in create
  | auth, __ = ProviderAuthentication.objects.get_or_create(**authentication)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
  | return getattr(self.get_queryset(), name)(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 541, in get_or_create
  | return self._create_object_from_params(kwargs, params)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 583, in _create_object_from_params
  | raise e
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 575, in _create_object_from_params
  | obj = self.create(**params)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 422, in create
  | obj.save(force_insert=True, using=self.db)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
  | force_update=force_update, update_fields=update_fields)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
  | force_update, using, update_fields,
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table
  | result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert
  | using=using, raw=raw)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
  | return getattr(self.get_queryset(), name)(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
  | return query.get_compiler(using=using).execute_sql(return_id)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
  | cursor.execute(sql, params)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
  | return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
  | return executor(sql, params, many, context)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
  | return self.cursor.execute(sql, params)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
  | raise dj_exc_value.with_traceback(traceback) from exc_value
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
  | return self.cursor.execute(sql, params)
  | django.db.utils.IntegrityError: duplicate key value violates unique constraint "api_providerauthentication_provider_resource_name_key"
  | DETAIL:  Key (provider_resource_name)=(549fc82c-6d7b-44bd-8e5e-f4931aca91b1) already exists.

```

**Comment by dchorvat1** [comment]
@adberglund Can we still reproduce this? I tried adding two OCP providers with same `provider_resource_name`, and API returned correct 400 response

**Comment by adberglund** [comment]
@dchorvat1 Looks fixed in CI. Closing
