### ISSUE TITLE
providers endpoint returning 500 after adding azure provider

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#1421]
**Describe the bug**
After I added an Azure provider, GET to `/providers/` resulted in 500 responses

**To Reproduce**
1. Add azure provider
2. GET `/providers/`
3. See error

**Expected behavior**
No errors

**Traceback**
```
[2019-11-19 11:39:36,602] INFO: API: /api/cost-management/v1/providers/3e399195-276f-4491-96f7-d81af1adf4c0/ -- ACCOUNT: 6089719 USER: insights-qa
[2019-11-19 11:39:36,635] ERROR: Internal Server Error: /api/cost-management/v1/providers/3e399195-276f-4491-96f7-d81af1adf4c0/
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/app-root/src/koku/api/provider/view.py", line 177, in destroy
    manager = ProviderManager(uuid)
  File "/opt/app-root/src/koku/api/provider/provider_manager.py", line 56, in __init__
    self.sources_model = Sources.objects.get(koku_uuid=self._uuid)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 412, in get
    (self.model._meta.object_name, num)
api.provider.models.Sources.MultipleObjectsReturned: get() returned more than one Sources -- it returned 2!
```

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Commit Hash from status endpoint: 1fc823b5bd5610de48bd9450c3ff7cb34e545c16

**Additional context**

**Comment by infinitewarp** [comment]
We believe this was fixed very recently by enforcing only one source-provider exists. @dchorvat1 Please take a look!

**Comment by infinitewarp** [comment]
See also: https://github.com/project-koku/koku/pull/1430

**Comment by dchorvat1** [comment]
I tried to reproduce this and it seems fixed, will reopen if it occurs again
