### ISSUE TITLE
Azure summarization fails with ocp on aws providers in the environment

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#1489]
**Describe the bug**
With OCP on AWS providers present in the database, the worker tries to update OCP on AWS summary tables for Azure provider after ingesting Azure data.

**To Reproduce**
1. Add some ocp on aws providers with data
2. Add Azure provider, ingest data
3. See error

**Expected behavior**
No errors during summarization 

**Logs**
```
[2019-12-05 09:51:26,831] INFO: Updating OpenShift on AWS summary table for 
	Schema: acct6089719 
	Provider: 1acfc5ec-2931-422a-9335-0fa1dca8906f 
	Dates: 2019-12-01 - 2019-12-31
	Cluster ID: test2-ocp-charlie, AWS Bill IDs: ['1245']
[2019-12-05 09:51:26,907] INFO: Updating reporting_ocpawscostlineitem_daily_summary from 2019-12-01 to 2019-12-31.
[2019-12-05 09:51:27,503] INFO: Finished updating reporting_ocpawscostlineitem_daily_summary.
[2019-12-05 09:51:27,605] INFO: Updating reporting_ocpusagelineitem_daily_summary from 2019-12-01 to 2019-12-31.
[2019-12-05 09:51:27,617] INFO: Finished updating reporting_ocpusagelineitem_daily_summary.
[2019-12-05 09:51:27,630] INFO: Updating OpenShift on AWS summary table for 
	Schema: acct6089719 
	Provider: 1acfc5ec-2931-422a-9335-0fa1dca8906f 
	Dates: 2019-12-01 - 2019-12-31
	Cluster ID: test1-ocp-bravo, AWS Bill IDs: ['1240']
[2019-12-05 09:51:27,714] INFO: Updating reporting_ocpawscostlineitem_daily_summary from 2019-12-01 to 2019-12-31.
[2019-12-05 09:51:27,804] ERROR: Task failed: relation "reporting_aws_tags" already exists
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateTable: relation "reporting_aws_tags" already existsThe above exception was the direct cause of the following exception:Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 161, in _inner
    reraise(*exc_info)
  File "/opt/app-root/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/opt/app-root/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 156, in _inner
    return f(*args, **kwargs)
  File "/opt/app-root/src/koku/masu/processor/tasks.py", line 241, in update_summary_tables
    updater.update_summary_tables(start_date, end_date)
  File "/opt/app-root/src/koku/masu/processor/report_summary_updater.py", line 169, in update_summary_tables
    end_date
  File "/opt/app-root/src/koku/masu/processor/ocp/ocp_cloud_summary_updater.py", line 72, in update_summary_tables
    ocp_provider_uuid, infra_provider_uuid, start_date, end_date
  File "/opt/app-root/src/koku/masu/processor/ocp/ocp_cloud_summary_updater.py", line 108, in update_aws_summary_tables
    aws_bill_ids
  File "/opt/app-root/src/koku/masu/database/aws_report_db_accessor.py", line 306, in populate_ocp_on_aws_cost_daily_summary
    table_name, summary_sql, start_date, end_date, bind_params=list(summary_sql_params))
  File "/opt/app-root/src/koku/masu/database/report_db_accessor_base.py", line 371, in _execute_raw_sql_query
    cursor.execute(sql, params=bind_params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "reporting_aws_tags" already exists[2019-12-05 09:51:27,804: ERROR/ForkPoolWorker-1] Task failed: relation "reporting_aws_tags" already exists
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateTable: relation "reporting_aws_tags" already existsThe above exception was the direct cause of the following exception:Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 161, in _inner
    reraise(*exc_info)
  File "/opt/app-root/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/opt/app-root/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 156, in _inner
    return f(*args, **kwargs)
  File "/opt/app-root/src/koku/masu/processor/tasks.py", line 241, in update_summary_tables
    updater.update_summary_tables(start_date, end_date)
  File "/opt/app-root/src/koku/masu/processor/report_summary_updater.py", line 169, in update_summary_tables
    end_date
  File "/opt/app-root/src/koku/masu/processor/ocp/ocp_cloud_summary_updater.py", line 72, in update_summary_tables
    ocp_provider_uuid, infra_provider_uuid, start_date, end_date
  File "/opt/app-root/src/koku/masu/processor/ocp/ocp_cloud_summary_updater.py", line 108, in update_aws_summary_tables
    aws_bill_ids
  File "/opt/app-root/src/koku/masu/database/aws_report_db_accessor.py", line 306, in populate_ocp_on_aws_cost_daily_summary
    table_name, summary_sql, start_date, end_date, bind_params=list(summary_sql_params))
  File "/opt/app-root/src/koku/masu/database/report_db_accessor_base.py", line 371, in _execute_raw_sql_query
    cursor.execute(sql, params=bind_params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "reporting_aws_tags" already exists[2019-12-05 09:51:27,811: INFO/ForkPoolWorker-1] masu.processor.tasks.update_summary_tables[9e15f706-1d2e-4139-ae26-3629c363cbc8]: update_summary_tables called with args:
 schema_name: acct1460290,
 provider: GCP,
 start_date: 2019-12-03,
 end_date: 2019-12-05,
 manifest_id: 16435
[2019-12-05 09:51:27,900] ERROR: Task failed: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/app-root/src/koku/masu/processor/report_summary_updater.py", line 68, in __init__
    self._updater, self._ocp_cloud_updater = self._set_updater()
TypeError: 'NoneType' object is not iterableDuring handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 161, in _inner
    reraise(*exc_info)
  File "/opt/app-root/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/opt/app-root/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 156, in _inner
    return f(*args, **kwargs)
  File "/opt/app-root/src/koku/masu/processor/tasks.py", line 238, in update_summary_tables
    updater = ReportSummaryUpdater(schema_name, provider_uuid, manifest_id)
  File "/opt/app-root/src/koku/masu/processor/report_summary_updater.py", line 70, in __init__
    raise ReportSummaryUpdaterError(err)
masu.processor.report_summary_updater.ReportSummaryUpdaterError: 'NoneType' object is not iterable
[2019-12-05 09:51:27,900: ERROR/ForkPoolWorker-1] Task failed: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/app-root/src/koku/masu/processor/report_summary_updater.py", line 68, in __init__
    self._updater, self._ocp_cloud_updater = self._set_updater()
TypeError: 'NoneType' object is not iterableDuring handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 161, in _inner
    reraise(*exc_info)
  File "/opt/app-root/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/opt/app-root/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 156, in _inner
    return f(*args, **kwargs)
  File "/opt/app-root/src/koku/masu/processor/tasks.py", line 238, in update_summary_tables
    updater = ReportSummaryUpdater(schema_name, provider_uuid, manifest_id)
  File "/opt/app-root/src/koku/masu/processor/report_summary_updater.py", line 70, in __init__
    raise ReportSummaryUpdaterError(err)
masu.processor.report_summary_updater.ReportSummaryUpdaterError: 'NoneType' object is not iterable
```

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Commit Hash from status endpoint: cd2bf064b7ef440cd6f629d5d6654342e3468980

**Additional context**
Tested on CI, also happens in smoke tests against stable branch.
@lcouzens said he couldn't reproduce this against local deployment

**Comment by infinitewarp** [comment]
Notes for whoever picks this up: We make some temp tables that need to have more unique names. We also have some processing that shouldn't be getting called for Azure.

**Comment by lcouzens** [comment]
Looks like we have a similar issue when adding ocp on azure data then an aws provider too.

```[2019-12-06 19:04:29,971] INFO: Updating reporting_ocpazurecostlineitem_daily_summary from 2019-12-01 to 2019-12-31.
[2019-12-06 19:04:30,057] ERROR: Task failed: relation "reporting_azure_tags" already exists
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateTable: relation "reporting_azure_tags" already exists
```

**Comment by lcouzens** [comment]
Verified
Commit: e9cc5a4d8852d71100a6a1db783bf1a1e48c4eca
