### ISSUE TITLE
group_by[and:value] results in 500s for AWS/OCP on AWS 

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#1542]
I suspect that `account` isn't making it into the annotations in the query handler.

**Describe the bug**
Using group_by[and:value] in cost report requests for AWS and OCP on AWS providers returns 500 error. 
We get correct 200 response for Openshift and Azure cost reports

**To Reproduce**
1. GET `https://ci.cloud.redhat.com/api/cost-management/v1/reports/openshift/infrastructures/aws/costs/?group_by[and:project]=te&group_by[and:project]=ch`

2. GET  `https://ci.cloud.redhat.com/api/cost-management/v1/reports/aws/costs/?group_by[and:account]=7777&group_by[and:account]=4444`

3. See errors

**Expected behavior**
No errors

**Logs**
```
[2019-12-12 09:16:28,900] INFO None API: /api/cost-management/v1/reports/aws/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[and:account]=7777&group_by[and:account]=4444&order_by[cost]=desc -- ACCOUNT: 6089719 USER: insights-qa
[2019-12-12 09:16:28,941] ERROR None Internal Server Error: /api/cost-management/v1/reports/aws/costs/
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1768, in add_fields
    join_info = self.setup_joins(name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1504, in setup_joins
    names[:pivot], opts, allow_many, fail_on_missing=True,
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1420, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'account' into field. Choices are: account_alias, account_alias_id, availability_zone, blended_cost, blended_rate, cost_entry_bill, cost_entry_bill_id, currency_code, date, id, instance_type, markup_cost, normalization_factor, normalized_usage_amount, product_code, product_family, public_on_demand_cost, public_on_demand_rate, region, resource_count, resource_ids, tags, tax_type, unblended_cost, unblended_rate, unit, usage_account_id, usage_amount, usage_end, usage_startDuring handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/vary.py", line 20, in inner_func
    response = func(*args, **kwargs)
  File "/opt/app-root/src/koku/api/report/view.py", line 157, in get
    output = handler.execute_query()
  File "/opt/app-root/src/koku/api/report/aws/query_handler.py", line 203, in execute_query
    query_data = query_data.values(*query_group_by).annotate(**annotations)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 798, in values
    clone = self._values(*fields, **expressions)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 793, in _values
    clone.query.set_values(fields)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 2020, in set_values
    self.add_fields(field_names, True)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1791, in add_fields
    "Choices are: %s" % (name, ", ".join(names)))
django.core.exceptions.FieldError: Cannot resolve keyword 'account' into field. Choices are: account_alias, account_alias_id, availability_zone, blended_cost, blended_rate, cost_entry_bill, cost_entry_bill_id, currency_code, date, id, instance_type, markup_cost, normalization_factor, normalized_usage_amount, product_code, product_family, public_on_demand_cost, public_on_demand_rate, region, resource_count, resource_ids, tags, tax_type, unblended_cost, unblended_rate, unit, usage_account_id, usage_amount, usage_end, usage_start
```

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox 
 - Commit Hash from status endpoint: 88f941102c430aa69dd11fda69962b88ef27782a

**Additional context**
tested on CI, not reproducible on QA

**Comment by dchorvat1** [comment]
verified, 5488c19971b6e906ff980e1f2c8c50a99dae9d7d
