### ISSUE TITLE
GroupBy combinations break with tags

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#1589]
**Describe the bug**
Users want the ability to filter using multiple combinations. In the UI details page; for example, I may want to group_by project, then group_by node and/or tag.

It turns out that `group_by[project]=*&group_by[cluster]=ocp` works, but `group_by[project]=*&group_by[tag:environment]=dev` generates a 500 error.

**To Reproduce**

1. Go to: /api/cost-management/v1/reports/openshift/infrastructures/all/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[project]=*&group_by[tag:environment]=*&order_by[cost]=desc

2. Go to: /api/cost-management/v1/reports/openshift/infrastructures/all/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[or:project]=*&group_by[or:tag:environment]=*&order_by[cost]=desc

3. See 500 error

**Expected behavior**
Expecting any group_by combination of project, cluster, node, and/or tag etc. not to error.

**Screenshots**
For reference, please see the issue below showing our new UI filtering feature
https://github.com/project-koku/koku-ui/issues/1111

**Traceback**

```

[2020-01-07 15:53:16,049] INFO None API: /api/cost-management/v1/reports/openshift/infrastructures/all/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[project]=*&group_by[or:tag:environment]=dev&order_by[cost]=desc -- ACCOUNT: 1460290 USER: jalberts@redhat.com
--
  | [2020-01-07 15:53:16,587] ERROR None Internal Server Error: /api/cost-management/v1/reports/openshift/infrastructures/all/costs/
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
  | response = get_response(request)
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
  | response = self.process_exception_by_middleware(e, request)
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
  | response = wrapped_callback(request, *callback_args, **callback_kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
  | return view_func(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
  | return self.dispatch(request, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
  | response = self.handle_exception(exc)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
  | self.raise_uncaught_exception(exc)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
  | raise exc
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
  | response = handler(request, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/vary.py", line 20, in inner_func
  | response = func(*args, **kwargs)
  | File "/opt/app-root/src/koku/api/report/view.py", line 157, in get
  | output = handler.execute_query()
  | File "/opt/app-root/src/koku/api/report/ocp_aws/query_handler.py", line 43, in execute_query
  | query = q_table.objects.filter(self.query_filter)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
  | return getattr(self.get_queryset(), name)(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
  | return self._filter_or_exclude(False, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
  | clone.query.add_q(Q(*args, **kwargs))
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
  | clause, _ = self._add_q(q_object, self.used_aliases)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1312, in _add_q
  | current_negated, allow_joins, split_subq, simple_col)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
  | split_subq=split_subq, simple_col=simple_col,
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1190, in build_filter
  | lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1049, in solve_lookup_type
  | _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1420, in names_to_path
  | "Choices are: %s" % (name, ", ".join(available)))
  | django.core.exceptions.FieldError: Cannot resolve keyword 'tags' into field. Choices are: account_alias, account_alias_id, availability_zone, cluster_alias, cluster_id, currency_code, data_source, id, instance_type, namespace, node, pod_cost, pod_labels, product_code, product_family, project_markup_cost, region, resource_id, source_type, unblended_cost, unit, usage_account_id, usage_amount, usage_end, usage_start
```

**Comment by dlabrecq** [comment]
Marking high-priority because tag filtering is a highly desired feature for the mid-January release.

**Comment by dlabrecq** [comment]
Further testing shows there's something about the ordering. This works...
`group_by[and:tag:environment]=*&group_by[and:project]=cost&group_by[and:node]=compute_2`

but, this causes a 500 error
`group_by[and:project]=cost&group_by[and:node]=compute_2&group_by[and:tag:environment]=*`

**Comment by lcouzens** [comment]
Verified
Commit: de6004607a845898ca36b4e1e573efe37a47096b
