### ISSUE TITLE
Cannot add Provider using HTML form in Browsable API

### ISSUE THREAD

**Issue by maskarb** [project-koku/koku#1626]
**Describe the bug**
Adding a provider with the HTML form in the browsable API results in AttributeError.

**To Reproduce**
1. Go to [http://localhost:8000/api/cost-management/v1/providers/](http://localhost:8000/api/cost-management/v1/providers/)
2. Try to add a new provider using the HTML form. (See screenshot)
3. See error

```
koku_server       | [2020-01-20 14:25:03,256] ERROR None Internal Server Error: /api/cost-management/v1/providers/
koku_server       | Traceback (most recent call last):
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
koku_server       |     response = get_response(request)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
koku_server       |     response = self.process_exception_by_middleware(e, request)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
koku_server       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
koku_server       |     return view_func(*args, **kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
koku_server       |     return self.dispatch(request, *args, **kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
koku_server       |     response = self.handle_exception(exc)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
koku_server       |     self.raise_uncaught_exception(exc)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
koku_server       |     raise exc
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
koku_server       |     response = handler(request, *args, **kwargs)
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
koku_server       |     response = view_func(request, *args, **kwargs)
koku_server       |   File "/koku/koku/api/provider/view.py", line 132, in create
koku_server       |     request.data['type'] = request.data.get('type', '').lower()
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/http/request.py", line 459, in __setitem__
koku_server       |     self._assert_mutable()
koku_server       |   File "/opt/app-root/lib/python3.6/site-packages/django/http/request.py", line 456, in _assert_mutable
koku_server       |     raise AttributeError("This QueryDict instance is immutable")
koku_server       | AttributeError: This QueryDict instance is immutable
koku_server       | [2020-01-20 14:25:03,261] ERROR None "POST /api/cost-management/v1/providers/ HTTP/1.1" 500 122437
```

**Expected behavior**
Successfully add provider using the HTML form.

**Screenshots**
Provider added (with switched out arn)
![Screen Shot 2020-01-20 at 9 42 28 AM](https://user-images.githubusercontent.com/19751919/72735270-76dcad00-3b69-11ea-81a6-98a6e4c763a1.png)

**Additional context**
This HTML form _does_ exist in the production API. I'm not sure what value there is to having the form in the browsable API anymore and it may be worth trying to figure out how to remove it. We can still add providers just fine using the Raw Data form or POSTing directly to the API.

When we added support for Azure, we needed to introduce the Credentials and Data Source fields which only accept JSON input. Since these fields are JSON, I don't think it's too much of a stretch to require the entire POST to be in JSON format instead of using this HTML format.

**Comment by lcouzens** [comment]
Verified
Commit: 52b3160188891772e88a6fb171adbcc926fc1f90
