### ISSUE TITLE
OCP on cloud 500 when grouping by tag

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#1647]
**Describe the bug**
Ocp on cloud infrastructure api returns 500 when we attempt to group the results by tags along with other group_by.

**To Reproduce**
1. Go to `/v1/reports/openshift/infrastructures/all/costs/?group_by[and:project]=*&group_by[and:tag:environment]=smoke_test_run_sample_long_tag`
2. See error

**Expected behavior**
No errors, correct result from the API 

**Traceback**
```

[2020-01-27 13:35:32,764] ERROR None Internal Server Error: /api/cost-management/v1/reports/openshift/infrastructures/all/costs/
--
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
  | response = get_response(request)
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
  | response = self.process_exception_by_middleware(e, request)
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
  | response = wrapped_callback(request, *callback_args, **callback_kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
  | return view_func(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
  | return self.dispatch(request, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
  | response = self.handle_exception(exc)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
  | self.raise_uncaught_exception(exc)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
  | raise exc
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
  | response = handler(request, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/vary.py", line 20, in inner_func
  | response = func(*args, **kwargs)
  | File "/opt/app-root/src/koku/api/report/view.py", line 157, in get
  | output = handler.execute_query()
  | File "/opt/app-root/src/koku/api/report/ocp_aws/query_handler.py", line 44, in execute_query
  | query = q_table.objects.filter(self.query_filter)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
  | return getattr(self.get_queryset(), name)(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
  | return self._filter_or_exclude(False, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
  | clone.query.add_q(Q(*args, **kwargs))
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
  | clause, _ = self._add_q(q_object, self.used_aliases)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1312, in _add_q
  | current_negated, allow_joins, split_subq, simple_col)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
  | split_subq=split_subq, simple_col=simple_col,
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1190, in build_filter
  | lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1049, in solve_lookup_type
  | _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1420, in names_to_path
  | "Choices are: %s" % (name, ", ".join(available)))
  | django.core.exceptions.FieldError: Cannot resolve keyword 'tags' into field. Choices are: account_alias, account_alias_id, availability_zone, cluster_alias, cluster_id, currency_code, data_source, id, instance_type, namespace, node, pod_cost, pod_labels, product_code, product_family, project_markup_cost, region, resource_id, source_type, unblended_cost, unit, usage_account_id, usage_amount, usage_end, usage_start
```

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Commit Hash from status endpoint: 63bd970c6623cbb3ebb47da68eafddfd50d8bc8e

**Additional context**

**Comment by dlabrecq** [comment]
This may be a dup of https://github.com/project-koku/koku/issues/1589

**Comment by dchorvat1** [comment]
You're right, it looks like the same issue. Closing this
