### ISSUE TITLE
Cost Model Delete Triggers Update Charge with Invalid Date Range

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1668]
**Describe the bug**
When a cost model is deleted it triggers a charge calculation task, but is not respecting the newly required start_date and end_date. 

**To Reproduce**
1. Create a cost model
2. Attach it to an existing provider
3. Delete a cost model
4. Watch worker logs for failure

**Expected behavior**
We need a way to clean up all derived cost calculations for the associated providers attached to a cost model. Until we "version" cost models by a date range, we should probably have a way to delete all derived cost calculations.

**Additional context**
We just added in the date range handling for derived cost. 

**Traceback**
```
[2020-01-29 19:40:47,308] ERROR 2bdd7405-0d98-45d2-a61f-e7471c96ccf4 Task failed: Cannot use None as a query value
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/koku/koku/masu/processor/tasks.py", line 319, in update_charge_info
    updater.update_charge_info(start_date, end_date)
  File "/koku/koku/masu/processor/report_charge_updater.py", line 91, in update_charge_info
    self._updater.update_summary_charge_info(start_date, end_date)
  File "/koku/koku/masu/processor/ocp/ocp_report_charge_updater.py", line 330, in update_summary_charge_info
    self._update_pod_charge(start_date, end_date)
  File "/koku/koku/masu/processor/ocp/ocp_report_charge_updater.py", line 225, in _update_pod_charge
    cpu_usage = report_accessor.get_pod_usage_cpu_core_hours(start_date, end_date, self._cluster_id)
  File "/koku/koku/masu/database/ocp_report_db_accessor.py", line 229, in get_pod_usage_cpu_core_hours
    reports = self._get_reports(table, filters)
  File "/koku/koku/masu/database/ocp_report_db_accessor.py", line 245, in _get_reports
    reports = self._get_db_obj_query(table).filter(**filters).all()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1121, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[2020-01-29 19:40:47,308: ERROR/ForkPoolWorker-1] Task failed: Cannot use None as a query value
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/koku/koku/masu/processor/tasks.py", line 319, in update_charge_info
    updater.update_charge_info(start_date, end_date)
  File "/koku/koku/masu/processor/report_charge_updater.py", line 91, in update_charge_info
    self._updater.update_summary_charge_info(start_date, end_date)
  File "/koku/koku/masu/processor/ocp/ocp_report_charge_updater.py", line 330, in update_summary_charge_info
    self._update_pod_charge(start_date, end_date)
  File "/koku/koku/masu/processor/ocp/ocp_report_charge_updater.py", line 225, in _update_pod_charge
    cpu_usage = report_accessor.get_pod_usage_cpu_core_hours(start_date, end_date, self._cluster_id)
  File "/koku/koku/masu/database/ocp_report_db_accessor.py", line 229, in get_pod_usage_cpu_core_hours
    reports = self._get_reports(table, filters)
  File "/koku/koku/masu/database/ocp_report_db_accessor.py", line 245, in _get_reports
    reports = self._get_db_obj_query(table).filter(**filters).all()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1121, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
```

**Comment by nbon12** [comment]
Andrew: "This is one I've seen in Koku-alerts channel. The entire summarization works on date_range. It originally took in start_date and end_date and did nothing with it. A spillover of that: When a cost model is deleted, it might also be when you detach a source from a cost model, it triggers a task which is how our cost is calculated. It tries to trigger the task with start date and end date, and since that's no longer allowed we get this traceback. When you're deleting the entire providers data, you want anything associated with that provider to be wiped. It is possible we could modify the task to be able to take some information about the provider to clear everything. Because it's a bug it's not 100% critical."

**Comment by lcouzens** [comment]
Verified
