### ISSUE TITLE
Test Case bugs for less than 30 day month

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#1681]
**Describe the bug**
The following test cases fail in the `master` branch due to the month of February.

```
FAIL: test_update_summary_tables_finalized_bill (masu.test.processor.aws.test_aws_report_summary_updater.AWSReportSummaryUpdaterTest)
Test that summary tables are run for a full month.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.6.7/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/project-koku/koku/koku/masu/test/processor/aws/test_aws_report_summary_updater.py", line 327, in test_update_summary_tables_finalized_bill
    self.assertEqual(mock_daily.call_args_list, expected_calls)
AssertionError: [call[59 chars]7']),
 call(datetime.date(2020, 2, 7), datetim[313 chars]7'])] != [call[59 chars]7']), call(datetime.date(2020, 2, 7), datetime[237 chars]7'])]
======================================================================
FAIL: test_update_summary_tables_new_bill (masu.test.processor.aws.test_aws_report_summary_updater.AWSReportSummaryUpdaterTest)
Test that summary tables are run for a full month.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.6.7/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/project-koku/koku/koku/masu/test/processor/aws/test_aws_report_summary_updater.py", line 165, in test_update_summary_tables_new_bill
    self.assertEqual(mock_daily.call_args_list, expected_calls)
AssertionError: [call[59 chars]9']),
 call(datetime.date(2020, 2, 7), datetim[313 chars]9'])] != [call[59 chars]9']), call(datetime.date(2020, 2, 7), datetime[237 chars]9'])]
======================================================================
FAIL: test_azure_update_summary_tables_new_bill (masu.test.processor.azure.test_azure_report_summary_updater.AzureReportSummaryUpdaterTest)
Test that summary tables are run for a full month.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.6.7/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/project-koku/koku/koku/masu/test/processor/azure/test_azure_report_summary_updater.py", line 158, in test_azure_update_summary_tables_new_bill
    self.assertEqual(mock_summary.call_args_list, expected_calls)
AssertionError: [call[59 chars]9']),
 call(datetime.date(2020, 2, 7), datetim[313 chars]9'])] != [call[59 chars]9']), call(datetime.date(2020, 2, 7), datetime[237 chars]9'])]
======================================================================
FAIL: test_update_summary_tables_new_period (masu.test.processor.ocp.test_ocp_report_summary_updater.OCPReportSummaryUpdaterTest)
Test that summary tables are run for a full month.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.6.7/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/project-koku/koku/koku/masu/test/processor/ocp/test_ocp_report_summary_updater.py", line 197, in test_update_summary_tables_new_period
    self.assertEqual(mock_daily.call_args_list, expected_calls)
AssertionError: [call[70 chars]-1'),
 call(datetime.date(2020, 2, 7), datetim[368 chars]-1')] != [call[70 chars]-1'), call(datetime.date(2020, 2, 7), datetime[281 chars]-1')]
----------------------------------------------------------------------
```

**To Reproduce**
1. Clone repo
2. Install dependencies (`pipenv install --dev`) and `pipenv shell`
3. Run `tox`

**Expected behavior**
Test should pass even in February.

**Comment by lcouzens** [comment]
Verified
