### ISSUE TITLE
Data summarization failures

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#1737]
**Describe the bug**
Data summarization on CI fails with following error, it could be a regression from https://github.com/project-koku/koku/pull/1733

**To Reproduce**
1. Add a provider (I tested this with AWS/OCP providers)
2. Ingest some data
3. See error

**Expected behavior**
No errors

**Traceback from worker logs:**
```
[2020-02-12 11:39:04,195] INFO dc7c3be6-b13b-40dd-979c-55b461488520 Updating reporting_awstags_summary
[2020-02-12 11:39:04,583] ERROR dc7c3be6-b13b-40dd-979c-55b461488520 Task failed: null value in column "cost_entry_bill_id" violates not-null constraint
DETAIL:  Failing row contains (273, environment, {cool-a,cool-b}, null).
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "cost_entry_bill_id" violates not-null constraint
DETAIL:  Failing row contains (273, environment, {cool-a,cool-b}, null).
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 161, in _inner
    reraise(*exc_info)
  File "/opt/app-root/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/opt/app-root/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 156, in _inner
    return f(*args, **kwargs)
  File "/opt/app-root/src/koku/masu/processor/tasks.py", line 231, in update_summary_tables
    updater.update_summary_tables(start_date, end_date)
  File "/opt/app-root/src/koku/masu/processor/report_summary_updater.py", line 162, in update_summary_tables
    start_date, end_date = self._updater.update_summary_tables(start_date, end_date)
  File "/opt/app-root/src/koku/masu/processor/aws/aws_report_summary_updater.py", line 120, in update_summary_tables
    accessor.populate_tags_summary_table()
  File "/opt/app-root/src/koku/masu/database/aws_report_db_accessor.py", line 262, in populate_tags_summary_table
    self._execute_raw_sql_query(table_name, agg_sql, bind_params=list(agg_sql_params))
  File "/opt/app-root/src/koku/masu/database/report_db_accessor_base.py", line 346, in _execute_raw_sql_query
    cursor.execute(sql, params=bind_params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "cost_entry_bill_id" violates not-null constraint
DETAIL:  Failing row contains (273, environment, {cool-a,cool-b}, null).
```

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: firefox
 - Commit Hash from status endpoint: 7f641fa8ec42be6045713530e83f21f40bf79697

cc @maskarb

**Comment by dchorvat1** [comment]
verified
