### ISSUE TITLE
cannot accumulate arrays of different dimensionality

### ISSUE THREAD

**Issue by maskarb** [project-koku/koku#1804]
**Describe the bug**
While adding OCP-on-AWS or OCP-on-Azure data, the tags summary update fails with the following traceback:

```
koku_worker       | [2020-02-24 18:12:07,051] INFO 18680299-5e96-42ca-b405-70089d1f4927 Updating reporting_ocpazuretags_summary
koku_worker       | [2020-02-24 18:12:07,059] ERROR 18680299-5e96-42ca-b405-70089d1f4927 Task failed: cannot accumulate arrays of different dimensionality
koku_worker       | Traceback (most recent call last):
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
koku_worker       |     return self.cursor.execute(sql, params)
koku_worker       | psycopg2.errors.ArraySubscriptError: cannot accumulate arrays of different dimensionality
koku_worker       | 
koku_worker       | 
koku_worker       | The above exception was the direct cause of the following exception:
koku_worker       | 
koku_worker       | Traceback (most recent call last):
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
koku_worker       |     R = retval = fun(*args, **kwargs)
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
koku_worker       |     return self.run(*args, **kwargs)
koku_worker       |   File "/koku/koku/masu/processor/tasks.py", line 237, in update_summary_tables
koku_worker       |     updater.update_summary_tables(start_date, end_date)
koku_worker       |   File "/koku/koku/masu/processor/report_summary_updater.py", line 164, in update_summary_tables
koku_worker       |     self._ocp_cloud_updater.update_summary_tables(start_date, end_date)
koku_worker       |   File "/koku/koku/masu/processor/ocp/ocp_cloud_summary_updater.py", line 74, in update_summary_tables
koku_worker       |     self.update_azure_summary_tables(ocp_provider_uuid, infra_provider_uuid, start_date, end_date)
koku_worker       |   File "/koku/koku/masu/processor/ocp/ocp_cloud_summary_updater.py", line 152, in update_azure_summary_tables
koku_worker       |     accessor.populate_ocp_on_azure_tags_summary_table()
koku_worker       |   File "/koku/koku/masu/database/azure_report_db_accessor.py", line 225, in populate_ocp_on_azure_tags_summary_table
koku_worker       |     self._execute_raw_sql_query(table_name, agg_sql, bind_params=list(agg_sql_params))
koku_worker       |   File "/koku/koku/masu/database/report_db_accessor_base.py", line 346, in _execute_raw_sql_query
koku_worker       |     cursor.execute(sql, params=bind_params)
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
koku_worker       |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
koku_worker       |     return executor(sql, params, many, context)
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
koku_worker       |     return self.cursor.execute(sql, params)
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
koku_worker       |     raise dj_exc_value.with_traceback(traceback) from exc_value
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
koku_worker       |     return self.cursor.execute(sql, params)
koku_worker       | django.db.utils.DataError: cannot accumulate arrays of different dimensionality
koku_worker       | 
koku_worker       | [2020-02-24 18:12:07,059: ERROR/ForkPoolWorker-1] Task failed: cannot accumulate arrays of different dimensionality
koku_worker       | Traceback (most recent call last):
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
koku_worker       |     return self.cursor.execute(sql, params)
koku_worker       | psycopg2.errors.ArraySubscriptError: cannot accumulate arrays of different dimensionality
koku_worker       | 
koku_worker       | 
koku_worker       | The above exception was the direct cause of the following exception:
koku_worker       | 
koku_worker       | Traceback (most recent call last):
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
koku_worker       |     R = retval = fun(*args, **kwargs)
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
koku_worker       |     return self.run(*args, **kwargs)
koku_worker       |   File "/koku/koku/masu/processor/tasks.py", line 237, in update_summary_tables
koku_worker       |     updater.update_summary_tables(start_date, end_date)
koku_worker       |   File "/koku/koku/masu/processor/report_summary_updater.py", line 164, in update_summary_tables
koku_worker       |     self._ocp_cloud_updater.update_summary_tables(start_date, end_date)
koku_worker       |   File "/koku/koku/masu/processor/ocp/ocp_cloud_summary_updater.py", line 74, in update_summary_tables
koku_worker       |     self.update_azure_summary_tables(ocp_provider_uuid, infra_provider_uuid, start_date, end_date)
koku_worker       |   File "/koku/koku/masu/processor/ocp/ocp_cloud_summary_updater.py", line 152, in update_azure_summary_tables
koku_worker       |     accessor.populate_ocp_on_azure_tags_summary_table()
koku_worker       |   File "/koku/koku/masu/database/azure_report_db_accessor.py", line 225, in populate_ocp_on_azure_tags_summary_table
koku_worker       |     self._execute_raw_sql_query(table_name, agg_sql, bind_params=list(agg_sql_params))
koku_worker       |   File "/koku/koku/masu/database/report_db_accessor_base.py", line 346, in _execute_raw_sql_query
koku_worker       |     cursor.execute(sql, params=bind_params)
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
koku_worker       |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
koku_worker       |     return executor(sql, params, many, context)
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
koku_worker       |     return self.cursor.execute(sql, params)
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
koku_worker       |     raise dj_exc_value.with_traceback(traceback) from exc_value
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
koku_worker       |     return self.cursor.execute(sql, params)
koku_worker       | django.db.utils.DataError: cannot accumulate arrays of different dimensionality
```

**To Reproduce**
with clean db:
1. make create-test-customer
2. make load-test-customer-data start=2020-01-01 end=2020-02-24
3. Eventually see error in koku-worker logs

**Comment by lcouzens** [comment]
Verified
