### ISSUE TITLE
AWS Tags with Double Quote Failing JSON parsing

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1836]
**Describe the bug**
We combine AWS tags into a single JSON record when inserting AWS line items to the DB  and double quotes are causing invalid JSON.

**To Reproduce**
1. Add a tag key or value with double quotes in the name
2. Try to process data
3. Watch JSON go :boom:

**Expected behavior**
We should be able to load any tag/keys in to the DB. 

**Traceback**

```
[1;31m[2020-03-02 07:34:21,419] ERROR b22f01c7-696e-4286-a64f-de6ac4b4b052 Task failed: invalid input syntax for type json
DETAIL:  Token "canary" is invalid.
CONTEXT:  JSON data, line 1: ...": "welcomed-doberman-install", "owner": ""canary...
COPY reporting_awscostentrylineitem, line 21245, column tags: "{"createdBy": "IAMUser:dafkjadklfjdalk", "Name": "welcomed-doberman-install", "owner"..."
Traceback (most recent call last):
  File "/opt/app-root/src/koku/masu/processor/report_processor.py", line 114, in process
    return self._processor.process()
  File "/opt/app-root/src/koku/masu/processor/aws/aws_report_processor.py", line 151, in process
    self._save_to_db(AWS_CUR_TABLE_MAP["line_item"], report_db)
  File "/opt/app-root/src/koku/masu/processor/report_processor_base.py", line 124, in _save_to_db
    report_db_accessor.bulk_insert_rows(csv_file, temp_table, columns)
  File "/opt/app-root/src/koku/masu/database/report_db_accessor_base.py", line 154, in bulk_insert_rows
    cursor.copy_from(file_obj, table, sep=sep, columns=columns, null=null)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type json
DETAIL:  Token "canary" is invalid.
CONTEXT:  JSON data, line 1: ...": "welcomed-doberman-install", "owner": ""canary...
COPY reporting_awscostentrylineitem, line 21245, column tags: "{"createdBy": "IAMUser:dafkdjflkjadflkjadkl", "Name": "welcomed-doberman-install", "owner"..."


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app-root/src/koku/masu/processor/tasks.py", line 139, in get_report_files
    raise processing_error
  File "/opt/app-root/src/koku/masu/processor/tasks.py", line 127, in get_report_files
    _process_report_file(schema_name, provider_type, provider_uuid, report_dict)
  File "/opt/app-root/src/koku/masu/processor/_tasks/process.py", line 78, in _process_report_file
    processor.process()
  File "/opt/app-root/src/koku/masu/processor/report_processor.py", line 116, in process
    raise ReportProcessorError(str(err))
masu.processor.report_processor.ReportProcessorError: invalid input syntax for type json
DETAIL:  Token "canary" is invalid.
CONTEXT:  JSON data, line 1: ...": "welcomed-doberman-install", "owner": ""canary...
COPY reporting_awscostentrylineitem, line 21245, column tags: "{"createdBy": "IAMUser:afkljdfajkadflkjadf", "Name": "welcomed-doberman-install", "owner"..."
[0m
```

**Comment by lcouzens** [comment]
Ingestion of tags looks to be working however display of the tags in the tags api seems to be incorrect.

Expected tag `resourceTags/user:version: \"beta\"`
Tag at /aws/tags/ `"\\\"beta\\\""`

**Comment by adberglund** [comment]
@lcouzens I looked at this again, and I think via the API we just have to accept the extra characters here. In order to make it valid JSON we need the escape characters in the result. I think we need to lean on the API to parse the JSON escaped strings.

**Comment by lcouzens** [comment]
Verified
