### ISSUE TITLE
Intermittent Summarization Error: IndexError: list index out of range

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#1893]
**Describe the bug**
Ran into this issue running the smoke tests.

```
koku_worker       | [2020-03-12 00:17:39,948: INFO/ForkPoolWorker-1] [masu.processor.tasks.update_summary_tables(9d455cac-b821-4a5c-bcbf-44ab32839927 via b0a358d2-5e8f-44a9-bbff-a03caa201ebc)] update_summary_tables called with args:
koku_worker       |  schema_name: acct10001,
koku_worker       |  provider: AWS-local,
koku_worker       |  start_date: 2020-03-10,
koku_worker       |  end_date: 2020-03-12,
koku_worker       |  manifest_id: 20
koku_worker       | [2020-03-12 00:17:40,017] INFO b0a358d2-5e8f-44a9-bbff-a03caa201ebc Starting report data summarization for provider uuid: adec74a4-5adf-4f6c-ac7b-82291fef1343.
koku_worker       | [2020-03-12 00:17:40,042] ERROR b0a358d2-5e8f-44a9-bbff-a03caa201ebc Task failed: list index out of range
koku_worker       | Traceback (most recent call last):
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
koku_worker       |     R = retval = fun(*args, **kwargs)
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
koku_worker       |     return self.run(*args, **kwargs)
koku_worker       |   File "/koku/koku/masu/processor/tasks.py", line 236, in update_summary_tables
koku_worker       |     start_date, end_date = updater.update_daily_tables(start_date, end_date)
koku_worker       |   File "/koku/koku/masu/processor/report_summary_updater.py", line 141, in update_daily_tables
koku_worker       |     start_date, end_date = self._updater.update_daily_tables(start_date, end_date)
koku_worker       |   File "/koku/koku/masu/processor/aws/aws_report_summary_updater.py", line 62, in update_daily_tables
koku_worker       |     start_date, end_date = self._get_sql_inputs(start_date, end_date)
koku_worker       |   File "/koku/koku/masu/processor/aws/aws_report_summary_updater.py", line 141, in _get_sql_inputs
koku_worker       |     do_month_update = self._determine_if_full_summary_update_needed(bills[0])
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 309, in __getitem__
koku_worker       |     return qs._result_cache[0]
koku_worker       | IndexError: list index out of range
koku_worker       | [2020-03-12 00:17:40,042: ERROR/ForkPoolWorker-1] Task failed: list index out of range
koku_worker       | Traceback (most recent call last):
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
koku_worker       |     R = retval = fun(*args, **kwargs)
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
koku_worker       |     return self.run(*args, **kwargs)
koku_worker       |   File "/koku/koku/masu/processor/tasks.py", line 236, in update_summary_tables
koku_worker       |     start_date, end_date = updater.update_daily_tables(start_date, end_date)
koku_worker       |   File "/koku/koku/masu/processor/report_summary_updater.py", line 141, in update_daily_tables
koku_worker       |     start_date, end_date = self._updater.update_daily_tables(start_date, end_date)
koku_worker       |   File "/koku/koku/masu/processor/aws/aws_report_summary_updater.py", line 62, in update_daily_tables
koku_worker       |     start_date, end_date = self._get_sql_inputs(start_date, end_date)
koku_worker       |   File "/koku/koku/masu/processor/aws/aws_report_summary_updater.py", line 141, in _get_sql_inputs
koku_worker       |     do_month_update = self._determine_if_full_summary_update_needed(bills[0])
koku_worker       |   File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 309, in __getitem__
koku_worker       |     return qs._result_cache[0]
koku_worker       | IndexError: list index out of range
```

**To Reproduce**
1. Run `make docker-iqe-smokes-tests`
2. See error

**Expected behavior**
Summarization should not fail.

Place guard check on call.
https://github.com/project-koku/koku/blob/master/koku/masu/processor/aws/aws_report_summary_updater.py#L141

**Comment by lcouzens** [comment]
Verified
