### ISSUE TITLE
koku-listener exception stopped procssing messages

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#1978]
**Describe the bug**

```
[2020-03-26 20:00:34,108] INFO None Downloading report for:
 schema_name: acct1234567
 provider: OCP
 account (provider uuid): 896dad78-fa9a-4921-ba6d-3fcf6f285412
 report_month: March 2020
[2020-03-26 20:00:34,108] INFO None Available disk space: 16650657792 bytes (79.3%)
[2020-03-26 20:00:34,108] INFO None Attempting to get OCP manifest for 2020-03-01 00:00:00...
[2020-03-26 20:00:34,109] INFO None Looking for manifest at /var/tmp/masu/insights_local/01a754f2-8cdb-4f28-b2e1-8fe592d5c1e1/20200301-20200401
[2020-03-26 20:00:34,109] INFO None Inserting manifest database record for assembly_id: d5c858fb-100e-4b76-80c0-d59fa5d57520
[2020-03-26 20:00:34,111] INFO None No manifest entry found.  Adding for bill period start: 2020-03-01 00:00:00
[2020-03-26 20:00:34,122] INFO None Looking for manifest at /var/tmp/masu/insights_local/01a754f2-8cdb-4f28-b2e1-8fe592d5c1e1/20200301-20200401
[2020-03-26 20:00:34,123] INFO None manifest found: {'files': ['986b1b59-b03c-5f3f-90c2-07747a9fff11_openshift_usage_report.0.csv', '986b1b59-b03c-5f3f-90c2-07747a9fff11_openshift_usage_report.1.csv', '986b1b59-b03c-5f3f-90c2-07747a9fff11_openshift_usage_report.2.csv'], 'date': datetime.datetime(2020, 3, 26, 20, 0, 11, 799287), 'uuid': 'd5c858fb-100e-4b76-80c0-d59fa5d57520', 'cluster_id': '01a754f2-8cdb-4f28-b2e1-8fe592d5c1e1', 'manifest_path': '/var/tmp/masu/insights_local/01a754f2-8cdb-4f28-b2e1-8fe592d5c1e1/20200301-20200401/manifest.json'}
[2020-03-26 20:00:34,124] INFO None Deleted manifest file at /var/tmp/masu/insights_local/01a754f2-8cdb-4f28-b2e1-8fe592d5c1e1/20200301-20200401
[2020-03-26 20:00:34,131] INFO None Reports to be processed:
 schema_name: acct1234567
 provider: OCP
 provider_uuid: 896dad78-fa9a-4921-ba6d-3fcf6f285412
[2020-03-26 20:00:34,157] INFO None Processing complete for account {'authentication': '01a754f2-8cdb-4f28-b2e1-8fe592d5c1e1', 'customer_name': 'acct1234567', 'billing_source': {'bucket': ''}, 'provider_type': 'OCP', 'schema_name': 'acct1234567', 'provider_uuid': UUID('896dad78-fa9a-4921-ba6d-3fcf6f285412'), 'report_month': '2020-03-01'}
[2020-03-26 20:00:34,281] INFO None Summarization celery uuid: ce376d52-76e2-4fae-a3c8-0ed9d46f716d
[2020-03-26 20:00:34,281] INFO None Processing: {'files': ['986b1b59-b03c-5f3f-90c2-07747a9fff11_openshift_usage_report.0.csv', '986b1b59-b03c-5f3f-90c2-07747a9fff11_openshift_usage_report.1.csv', '986b1b59-b03c-5f3f-90c2-07747a9fff11_openshift_usage_report.2.csv'], 'date': datetime.datetime(2020, 3, 26, 20, 0, 11, 799287), 'uuid': 'd5c858fb-100e-4b76-80c0-d59fa5d57520', 'cluster_id': '01a754f2-8cdb-4f28-b2e1-8fe592d5c1e1', 'manifest_path': '/var/tmp/masu/tmpn10r80gh/tmp/korekuta-collect/01a754f2-8cdb-4f28-b2e1-8fe592d5c1e1/manifest.json'} complete.
[2020-03-26 20:00:47,587] INFO None Extracting Payload for msg: ConsumerRecord(topic='platform.upload.hccm', partition=1, offset=11785, timestamp=1585252847582, timestamp_type=0, key=b'', value=b'{"account":"525786","category":"tar","metadata":{"reporter":"","stale_timestamp":"0001-01-01T00:00:00Z"},"request_id":"8ac0c7a62be74d30846eca911eb337f5","principal":"3501353","service":"hccm","size":2883016,"url":"https://insights-upload-perma.s3.amazonaws.com/8ac0c7a62be74d30846eca911eb337f","timestamp":"2020-03-26T20:00:46.57794651Z"}' , checksum=None, serialized_key_size=0, serialized_value_size=1290, headers=())
Task exception was never retrieved
future: <Task finished coro=<process_messages() done, defined at /opt/app-root/src/koku/masu/external/kafka_msg_handler.py:305> exception=OSError("Not a gzipped file (b'{g')",)>
Traceback (most recent call last):
  File "/opt/app-root/src/koku/masu/external/kafka_msg_handler.py", line 318, in process_messages
    status, report_meta = handle_message(msg)
  File "/opt/app-root/src/koku/masu/external/kafka_msg_handler.py", line 232, in handle_message
    report_meta = extract_payload(value["url"])
  File "/opt/app-root/src/koku/masu/external/kafka_msg_handler.py", line 119, in extract_payload
    mytar.extractall(path=temp_dir)
  File "/opt/app-root/lib64/python3.6/tarfile.py", line 2002, in extractall
    for tarinfo in members:
  File "/opt/app-root/lib64/python3.6/tarfile.py", line 2413, in __iter__
    tarinfo = self.next()
  File "/opt/app-root/lib64/python3.6/tarfile.py", line 2297, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/opt/app-root/lib64/python3.6/tarfile.py", line 1092, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'{g')
```

**To Reproduce**
1. Upload a payload that is not tar.gz format
2. See error

**Expected behavior**
Listener should gracefully handle the invalid file format. Respond on the verify topic as invalid and delete the payload (any metrics for bad payloads should be incremented).

**Comment by lcouzens** [comment]
Verified!!
