### ISSUE TITLE
Listener seems to not reconnect to kafka if it loses connection.

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#2003]
**Describe the bug**
Listener pod does not auto reconnect to the kafka queue if it loses connection from kafka going down.

I noticed the other day that OCP data was not ingesting, after a quick look at the logs on CI I noticed that we had lost connection to kafka, seems like we don't have any monitoring to catch this and try to reconnect.

Heres what I pulled from the logs
```
Unable connect to "platform-mq-ci-kafka-bootstrap.platform-mq-ci.svc:9092": 
[2020-04-01 08:55:07,444] ERROR None ConnectionError: Unable to bootstrap from [('platform-mq-ci-kafka-bootstrap.platform-mq-ci.svc', 9092, <AddressFamily.AF_UNSPEC: 0>)]
Traceback (most recent call last):
  File "/opt/app-root/src/koku/masu/external/kafka_msg_handler.py", line 175, in send_confirmation
    await producer.start()
  File "/opt/app-root/lib/python3.6/site-packages/aiokafka/producer/producer.py", line 286, in start
    yield from self.client.bootstrap()
  File "/opt/app-root/lib/python3.6/site-packages/aiokafka/client.py", line 228, in bootstrap
    'Unable to bootstrap from {}'.format(self.hosts))
kafka.errors.ConnectionError: ConnectionError: Unable to bootstrap from [('platform-mq-ci-kafka-bootstrap.platform-mq-ci.svc', 9092, <AddressFamily.AF_UNSPEC: 0>)]
Task exception was never retrieved
future: <Task finished coro=<process_messages() done, defined at /opt/app-root/src/koku/masu/external/kafka_msg_handler.py:305> exception=KafkaMsgHandlerError('Unable to connect to kafka server.  Closing producer.',)>
Traceback (most recent call last):
  File "/opt/app-root/src/koku/masu/external/kafka_msg_handler.py", line 175, in send_confirmation
    await producer.start()
  File "/opt/app-root/lib/python3.6/site-packages/aiokafka/producer/producer.py", line 286, in start
    yield from self.client.bootstrap()
  File "/opt/app-root/lib/python3.6/site-packages/aiokafka/client.py", line 228, in bootstrap
    'Unable to bootstrap from {}'.format(self.hosts))
kafka.errors.ConnectionError: ConnectionError: Unable to bootstrap from [('platform-mq-ci-kafka-bootstrap.platform-mq-ci.svc', 9092, <AddressFamily.AF_UNSPEC: 0>)]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/app-root/src/koku/masu/external/kafka_msg_handler.py", line 321, in process_messages
    await send_confirmation(value["request_id"], status)
  File "/opt/app-root/src/koku/masu/external/kafka_msg_handler.py", line 180, in send_confirmation
    raise KafkaMsgHandlerError("Unable to connect to kafka server.  Closing producer.")
masu.external.kafka_msg_handler.KafkaMsgHandlerError: Unable to connect to kafka server.  Closing producer.
```

**Comment by lcouzens** [comment]
Struggling to find a easy way to reproduce this. Closing this and will keep monitoring CI.
