### ISSUE TITLE
koku-init container failing in CI

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#2018]
**Describe the bug**
We are seeing the following error in CI when trying to deploy the latest code.

```
=== Running migrate for schema acct6089719
Operations to perform:
  Apply all migrations: api, auth, contenttypes, cost_models, reporting, reporting_common, sessions
Running migrations:
  Applying cost_models.0001_initial_squashed_0018_auto_20200116_2048...
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.DuplicateTable: relation "cost_model_audit" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/src/koku/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/app-root/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/app-root/lib/python3.6/site-packages/tenant_schemas/management/commands/migrate_schemas.py", line 47, in handle
    executor.run_migrations(tenants=tenants)
  File "/opt/app-root/lib/python3.6/site-packages/tenant_schemas/migration_executors/base.py", line 61, in run_migrations
    self.run_tenant_migrations(tenants)
  File "/opt/app-root/lib/python3.6/site-packages/tenant_schemas/migration_executors/standard.py", line 9, in run_tenant_migrations
    run_migrations(self.args, self.options, self.codename, schema_name)
  File "/opt/app-root/lib/python3.6/site-packages/tenant_schemas/migration_executors/base.py", line 31, in run_migrations
    MigrateCommand(stdout=stdout, stderr=stderr).execute(*args, **options)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/opt/app-root/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 307, in create_model
    self.execute(sql, params or None)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "cost_model_audit" already exists
```

**Expected behavior**
Migration should finish successfully

**Comment by chambridge** [comment]
I've only found this when searching for a solution thus far:
https://stackoverflow.com/a/39805907

**Comment by chambridge** [comment]
Neither `--fake` or `--fake-initial` are valid flags for `manage.py migrate` now.

**Comment by adberglund** [comment]
Deployment succeeded after I repopulated the django_migrations table for the schema missing those records.
