### ISSUE TITLE
Unable to configure handler 'watchtower'

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#2058]
**Describe the bug**
Exception stops processing when cloud watch KEY/Secret are invalid.

```

Traceback (most recent call last):
  File "/opt/app-root/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/opt/app-root/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/opt/app-root/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/opt/app-root/lib/python3.6/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/opt/app-root/lib/python3.6/site-packages/celery/bin/base.py", line 289, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/opt/app-root/lib/python3.6/site-packages/celery/bin/base.py", line 509, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/opt/app-root/lib/python3.6/site-packages/celery/bin/base.py", line 531, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/utils.py", line 373, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/opt/app-root/lib/python3.6/site-packages/celery/bin/base.py", line 534, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/opt/app-root/lib/python3.6/site-packages/kombu/utils/imports.py", line 61, in symbol_by_name
    sys.exc_info()[2])
  File "/opt/app-root/lib/python3.6/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/opt/app-root/lib/python3.6/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/opt/app-root/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/app-root/src/koku/koku/__init__.py", line 2, in <module>
    from .celery import app as celery_app
  File "/opt/app-root/src/koku/koku/celery.py", line 49, in <module>
    django.setup()
  File "/opt/app-root/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/opt/app-root/lib/python3.6/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/config.py", line 802, in dictConfig
    dictConfigClass(config).configure()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/config.py", line 573, in configure
    '%r: %s' % (name, e))
ValueError: Couldn't import 'koku': Unable to configure handler 'watchtower': An error occurred (UnrecognizedClientException) when calling the CreateLogGroup operation: The security token included in the request is invalid.
```

**To Reproduce**
1. Set `CW_AWS_ACCESS_KEY_ID` and `CW_AWS_SECRET_ACCESS_KEY` to invalid values
2. Reset your environment
3. Restart koku

**Expected behavior**
Should not fail if cloudwatch key/secret are not valid.

**Comment by lcouzens** [comment]
Verified
