### ISSUE TITLE
Large OCP payloads are not successfully ingested

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#2129]
**Describe the bug**
When ingesting a large OCP payload the listener is failing to recover from an offset commit failure.

```
koku_listener     | [2020-05-08 13:14:20,821] INFO None Successfully extracted OCP for my-ocp-cluster/20200501-20200601
koku_listener     | OffsetCommit failed for group hccm-group due to group error ([Error 25] UnknownMemberIdError: hccm-group), will rejoin
koku_listener     | OffsetCommit failed for group hccm-group due to group error ([Error 25] UnknownMemberIdError: hccm-group), will rejoin
koku_listener     | Auto offset commit failed: [Error 25] UnknownMemberIdError: hccm-group
koku_listener     | Heartbeat failed: local member_id was not recognized; resetting and re-joining group
koku_listener     | Heartbeat session expired - marking coordinator dead
koku_listener     | Marking the coordinator dead (node 1)for group hccm-group.
koku_listener     | Exception in thread Thread-2:
koku_listener     | Traceback (most recent call last):
koku_listener     |   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
koku_listener     |     self.run()
koku_listener     |   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 864, in run
koku_listener     |     self._target(*self._args, **self._kwargs)
koku_listener     |   File "<decorator-gen-3>", line 2, in asyncio_worker_thread
koku_listener     |   File "/opt/app-root/lib/python3.6/site-packages/prometheus_client/context_managers.py", line 23, in wrapped
koku_listener     |     return func(*args, **kwargs)
koku_listener     |   File "/koku/koku/masu/external/kafka_msg_handler.py", line 414, in asyncio_worker_thread
koku_listener     |     loop.run_until_complete(listen_for_messages(consumer))
koku_listener     |   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
koku_listener     |     return future.result()
koku_listener     |   File "/koku/koku/masu/external/kafka_msg_handler.py", line 383, in listen_for_messages
koku_listener     |     async for msg in consumer:
koku_listener     |   File "/opt/app-root/lib/python3.6/site-packages/aiokafka/consumer/consumer.py", line 1220, in __anext__
koku_listener     |     return (yield from self.getone())
koku_listener     |   File "/opt/app-root/lib/python3.6/site-packages/aiokafka/consumer/consumer.py", line 1101, in getone
koku_listener     |     msg = yield from self._fetcher.next_record(partitions)
koku_listener     |   File "/opt/app-root/lib/python3.6/site-packages/aiokafka/consumer/fetcher.py", line 1051, in next_record
koku_listener     |     yield from waiter
koku_listener     | kafka.errors.UnknownMemberIdError: [Error 25] UnknownMemberIdError: hccm-group
koku_listener     | 
koku_listener exited with code 0
(koku) ➜  koku git:(listener_fix) 
```

**To Reproduce**
Generate large OCP payload and upload through ingress service.

```
(nise_fork) ➜  nise_fork git:(lint) ✗ nise --ocp --file-row-limit 1500000 --ocp-cluster-id my-ocp-cluster --static-report-file large_ocp.yml --insights-upload http://localhost:8080/api/ingress/v1/upload
Upload File: (/var/folders/ys/tpl5t1qs64345x9s630w2tkw0000gn/T/tmpnfii_b00.tar.gz) filesize is 33.1 MB.
File uploaded successfully.

Upload File: (/var/folders/ys/tpl5t1qs64345x9s630w2tkw0000gn/T/tmp2cqs7pok.tar.gz) filesize is 49.4 MB.
File uploaded successfully.

Upload File: (/var/folders/ys/tpl5t1qs64345x9s630w2tkw0000gn/T/tmp_s09zoxh.tar.gz) filesize is 10.2 KB.
File uploaded successfully.

(nise_fork) ➜  nise_fork git:(lint) ✗ 
```

**Expected behavior**
Processing should be successful.

**Comment by lcouzens** [comment]
Verified
