### ISSUE TITLE
Koku deployment failure: api.status.models.Status.MultipleObjectsReturned: get() returned more than one Status -- it returned 2!

### ISSUE THREAD

**Issue by LandoCalrizzian** [project-koku/koku#333]
Koku deployment is failing with 

> [2018-08-22 16:25:35 +0000] [50] [ERROR] Exception in worker process
> Traceback (most recent call last):
>   File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
>     worker.init_process()
>   File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
>     self.load_wsgi()
>   File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
>     self.wsgi = self.app.wsgi()
>   File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
>     self.callable = self.load()
>   File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
>     return self.load_wsgiapp()
>   File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
>     return util.import_app(self.app_uri)
>   File "/opt/app-root/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
>     __import__(module)
>   File "/opt/app-root/src/koku/koku/wsgi.py", line 33, in <module>
>     application = get_wsgi_application()
>   File "/opt/app-root/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
>     django.setup(set_prefix=False)
>   File "/opt/app-root/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/opt/app-root/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
>     app_config.ready()
>   File "/opt/app-root/src/koku/api/apps.py", line 41, in ready
>     self.startup_status()
>   File "/opt/app-root/src/koku/api/apps.py", line 55, in startup_status
>     status_info, _ = Status.objects.get_or_create()
>   File "/opt/app-root/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 486, in get_or_create
>     return self.get(**lookup), False
>   File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
>     (self.model._meta.object_name, num)
> api.status.models.Status.MultipleObjectsReturned: get() returned more than one Status -- it returned 2!

1. Deploy koku to OpenShift 

**Expected behavior**
Koku deployment successfull

**Context (please complete the following information):**
 - OS: OpenShift 3.9
 - Commit: https://github.com/project-koku/koku/tree/ff9b5ed8f17dcae4c59e5e0090ad3dd3d2b270ea

**Additional context**
Koku postgres deployment was successful

**Comment by LandoCalrizzian** [comment]
VERIFIED. Haven't encountered this error in 10+ deployments of koku
