### ISSUE TITLE
Traceback occurs in execute sum query

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#592]
**Describe the bug**

```
[2019-01-28 15:08:35,875] INFO: API: /r/insights/platform/cost-management/api/v1/reports/charges/ocp/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=daily&filter[limit]=5&group_by[project]=* -- ACCOUNT: xxxxx USER: yyyyyy
--
  | [2019-01-28 15:08:35,921] INFO: API: /r/insights/platform/cost-management/api/v1/reports/charges/ocp/ USER: insights-qa
  | [2019-01-28 15:08:35,989] ERROR: Internal Server Error: /r/insights/platform/cost-management/api/v1/reports/charges/ocp/
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
  | response = get_response(request)
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
  | response = self.process_exception_by_middleware(e, request)
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
  | response = wrapped_callback(request, *callback_args, **callback_kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
  | return view_func(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
  | return self.dispatch(request, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
  | response = self.handle_exception(exc)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
  | self.raise_uncaught_exception(exc)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
  | response = handler(request, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/decorators.py", line 54, in handler
  | return func(*args, **kwargs)
  | File "/opt/app-root/src/koku/api/report/ocp/view.py", line 350, in charges
  | OCPReportQueryHandler, **extras)
  | File "/opt/app-root/src/koku/api/report/view.py", line 214, in _generic_report
  | output = handler.execute_query()
  | File "/opt/app-root/src/koku/api/report/ocp/ocp_query_handler.py", line 168, in execute_query
  | return self.execute_sum_query()
  | File "/opt/app-root/src/koku/api/report/ocp/ocp_query_handler.py", line 136, in execute_sum_query
  | query_data = self.order_by(query_data, query_order_by)
  | File "/opt/app-root/src/koku/api/report/queries.py", line 615, in order_by
  | reverse=reverse)
  | TypeError: '<' not supported between instances of 'NoneType' and 'int'
  | 10.131.10.1 - - [28/Jan/2019:15:08:35 +0000] "GET /r/insights/platform/cost-management/api/v1/reports/charges/ocp/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=daily&filter[limit]=5&group_by[project]=* HTTP/1.1" 500 27 "https://access.redhat.com/insights/platform/cost-management/ " "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36"
```

**Comment by chambridge** [comment]
Has not been seen in the last month. Closing can be reopened.
