### ISSUE TITLE
Rates not getting applied if two providers have already been ingested

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#694]
**Describe the bug**
Rates not getting applied if two providers have already been ingested

**To Reproduce**
1. Add two OCP providers
2. Ingest data
3. Add rates to one provider
4. Hit /api/v1/update_charge/?provider_uuid={provider_uuid}&schema={account_id}
5. Nothing happens but we get a traceback in the masu logs.
```
[2019-03-02 15:59:17,024: INFO/ForkPoolWorker-1] masu.processor.tasks.update_charge_info[de80f27e-31a3-4810-8c0c-64280d289b1c]: update_charge_info called with args:
 schema_name: 6089719,
 provider_uuid: 86cdd952-d41d-4499-b86e-2d5eaa91be49
[2019-03-02 15:59:17,980: WARNING/ForkPoolWorker-1] [2019-03-02 15:59:17,980] INFO in ocp_report_charge_updater: Starting charge calculation updates.
[2019-03-02 15:59:17,980: INFO/ForkPoolWorker-1] Starting charge calculation updates.
[2019-03-02 15:59:17,998: ERROR/ForkPoolWorker-1] Task masu.processor.tasks.update_charge_info[de80f27e-31a3-4810-8c0c-64280d289b1c] raised unexpected: AttributeError("'ReportSchema' object has no attribute 'rates_rate'",)
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/app-root/src/masu/celery/__init__.py", line 75, in __call__
    return self.run(*args, **kwargs)
  File "/opt/app-root/src/masu/processor/tasks.py", line 256, in update_charge_info
    updater.update_charge_info()
  File "/opt/app-root/src/masu/processor/report_charge_updater.py", line 88, in update_charge_info
    self._updater.update_summary_charge_info()
  File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 252, in update_summary_charge_info
    self._update_pod_charge()
  File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 172, in _update_pod_charge
    cpu_usage_rates = rate_accessor.get_cpu_core_usage_per_hour_rates()
  File "/opt/app-root/src/masu/database/ocp_rate_db_accessor.py", line 70, in get_cpu_core_usage_per_hour_rates
    cpu_usage_rates = self.get_rates('cpu_core_usage_per_hour')
  File "/opt/app-root/src/masu/database/ocp_rate_db_accessor.py", line 65, in get_rates
    rate_entry = self._get_base_entry(value)
  File "/opt/app-root/src/masu/database/ocp_rate_db_accessor.py", line 48, in _get_base_entry
    getattr(self.report_schema, table_name),
AttributeError: 'ReportSchema' object has no attribute 'rates_rate'
```

**Expected behavior**
Rates should get applied to provider

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Chrome
 - Commit Hash from status endpoint: 4d67ef8cbc2f2a3c5dd0ff2505551903631d8620

**Additional context**
Rates seem to get applied ok if they have been added before initial ingest of data

**Comment by dccurtis** [comment]
Able to repro the problem where the other provider charges are being calculated, but did not experience the `AttributeError: 'ReportSchema' object has no attribute 'rates_rate` error

**Comment by lcouzens** [comment]
Verified
Commit: dd866691f654b4b4ffe91ad751b3db980946303c
