### ISSUE TITLE
API blows up if you try to use ?delta=cost on aws instance-type/storage endpoints

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#745]
**Describe the bug**
API blows up if you try to use ?delta=cost on aws instance-type/storage endpoints

**To Reproduce**
1. Go to 'v1/reports/aws/storage/?delta=cost'
2. See error

**Expected behavior**
Deltas shown or error message.
```
{
    "delta": [
        "\"cost\" is not a valid choice."
    ]
}
```

**Screenshots**
![Screenshot from 2019-03-15 15-39-00](https://user-images.githubusercontent.com/18352403/54443430-82389e00-4738-11e9-8699-adede03a6bab.png)

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Commit Hash from status endpoint: bb7fa6fd566be582a1b3c5d7b25bf08f1fa77a5b

**Additional context**
?delta=cost is working on aws/costs endpoint.
Error is shown if you try other invalid options.
```
{
    "delta": [
        "\"test\" is not a valid choice."
    ]
}
```

**Comment by chambridge** [comment]
No reason not to just make this work with `cost` as we provide that data back on this endpoint.

**Comment by lcouzens** [comment]
@chambridge Just noticed a similar issue on OCP volumes for usage/request deltas slightly different error but figured you might want to add it to this bug instead of a new one?

Basically cost works here but usage/request blows up the API here's the error I see locally on koku.

```server_1  | [2019-03-25 17:27:58,920] INFO: API: /api/v1/reports/openshift/volumes/ USER: user_dev
server_1  | [2019-03-25 17:27:59,029] ERROR: Internal Server Error: /api/v1/reports/openshift/volumes/
server_1  | Traceback (most recent call last):
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
server_1  |     response = get_response(request)
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
server_1  |     response = self.process_exception_by_middleware(e, request)
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
server_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
server_1  |     return view_func(*args, **kwargs)
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
server_1  |     return self.dispatch(request, *args, **kwargs)
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
server_1  |     response = self.handle_exception(exc)
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
server_1  |     self.raise_uncaught_exception(exc)
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
server_1  |     response = handler(request, *args, **kwargs)
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/rest_framework/decorators.py", line 55, in handler
server_1  |     return func(*args, **kwargs)
server_1  |   File "/koku/koku/api/report/ocp/view.py", line 439, in volume
server_1  |     return _generic_report(request, report='volume', provider='ocp')
server_1  |   File "/koku/koku/api/report/view.py", line 383, in _generic_report
server_1  |     output = handler.execute_query()
server_1  |   File "/koku/koku/api/report/ocp/ocp_query_handler.py", line 153, in execute_query
server_1  |     query_data = self.add_deltas(query_data, query_sum)
server_1  |   File "/koku/koku/api/report/ocp/ocp_query_handler.py", line 265, in add_deltas
server_1  |     return super().add_deltas(query_data, query_sum)
server_1  |   File "/koku/koku/api/report/queries.py", line 1455, in add_deltas
server_1  |     delta_group_by)
server_1  |   File "/koku/koku/api/report/queries.py", line 1400, in _create_previous_totals
server_1  |     .annotate(**delta_annotation)
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 1008, in annotate
server_1  |     clone.query.add_annotation(annotation, alias, is_summary=False)
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 988, in add_annotation
server_1  |     summarize=is_summary)
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/django/db/models/aggregates.py", line 39, in resolve_expression
server_1  |     c = super().resolve_expression(query, allow_joins, reuse, summarize)
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/django/db/models/expressions.py", line 597, in resolve_expression
server_1  |     c.source_expressions[pos] = arg.resolve_expression(query, allow_joins, reuse, summarize, for_save)
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/django/db/models/expressions.py", line 509, in resolve_expression
server_1  |     return query.resolve_ref(self.name, allow_joins, reuse, summarize)
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1570, in resolve_ref
server_1  |     join_info = self.setup_joins(field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse)
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1473, in setup_joins
server_1  |     names[:pivot], opts, allow_many, fail_on_missing=True,
server_1  |   File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1389, in names_to_path
server_1  |     "Choices are: %s" % (name, ", ".join(available)))
server_1  | django.core.exceptions.FieldError: Cannot resolve keyword 'persistentvolumeclaim_usage_gigabyte_hours' into field. Choices are: cluster_alias, cluster_id, date, id, namespace, node, persistentvolume, persistentvolumeclaim, persistentvolumeclaim_capacity_gigabyte, persistentvolumeclaim_capacity_gigabyte_months, persistentvolumeclaim_charge_gb_month, persistentvolumeclaim_usage_gigabyte_months, pod, storageclass, usage_end, usage_start, volume_labels, volume_request_storage_gigabyte_months
```
