### ISSUE TITLE
OpenShift tags query causes 500

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#831]
**Describe the bug**
Error occurs when querying tags. 500 with traceback.

**To Reproduce**

```

[2019-04-25 12:53:11,559] INFO: API: /api/cost-management/v1/tags/openshift/?filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&key_only=true -- ACCOUNT: 6193296 USER: cost-openshift
--
  | [2019-04-25 12:53:11,582] INFO: API: /api/cost-management/v1/tags/openshift/ USER: cost-openshift
  | [2019-04-25 12:53:11,597] ERROR: Internal Server Error: /api/cost-management/v1/tags/openshift/
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
  | return self.cursor.execute(sql, params)
  | psycopg2.errors.FeatureNotSupported: aggregate function calls cannot contain set-returning function calls
  | LINE 1: ...daily_summary"."pod_labels") AS "tag_keys", COUNT(jsonb_obje...
  | ^
  | HINT:  You might be able to move the set-returning function into a LATERAL FROM item.
  |  
  |  
  | The above exception was the direct cause of the following exception:
  |  
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
  | response = get_response(request)
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
  | response = self.process_exception_by_middleware(e, request)
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
  | response = wrapped_callback(request, *callback_args, **callback_kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
  | return view_func(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
  | return self.dispatch(request, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
  | response = self.handle_exception(exc)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
  | self.raise_uncaught_exception(exc)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
  | response = handler(request, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/rest_framework/decorators.py", line 55, in handler
  | return func(*args, **kwargs)
  | File "/opt/app-root/src/koku/api/tags/ocp/view.py", line 65, in ocp_tags
  | return _generic_report(request, provider='ocp', report='tags')
  | File "/opt/app-root/src/koku/api/report/view.py", line 387, in _generic_report
  | output = handler.execute_query()
  | File "/opt/app-root/src/koku/api/tags/queries.py", line 220, in execute_query
  | tag_data = self.get_tag_keys()
  | File "/opt/app-root/src/koku/api/tags/queries.py", line 165, in get_tag_keys
  | tag_keys_query = [tag.get('tag_keys') for tag in tag_keys_query]
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 274, in __iter__
  | self._fetch_all()
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
  | self._result_cache = list(self._iterable_class(self))
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 113, in __iter__
  | for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1049, in results_iter
  | results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1097, in execute_sql
  | cursor.execute(sql, params)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
  | return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
  | return executor(sql, params, many, context)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
  | return self.cursor.execute(sql, params)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
  | raise dj_exc_value.with_traceback(traceback) from exc_value
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
  | return self.cursor.execute(sql, params)
  | django.db.utils.NotSupportedError: aggregate function calls cannot contain set-returning function calls
  | LINE 1: ...daily_summary"."pod_labels") AS "tag_keys", COUNT(jsonb_obje...
  | ^
  | HINT:  You might be able to move the set-returning function into a LATERAL FROM item.
  |  
  | 10.128.2.1 - - [25/Apr/2019:12:53:11 +0000] "GET /api/cost-management/v1/tags/openshift/?filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&key_only=true HTTP/1.1" 500 27 "https://cloud.redhat.com/beta/apps/cost-management/ocp?group_by[project]=*&order_by[cost]=desc " "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
```

**Expected behavior**
Should get back the applicable set of tags.

**Comment by dchorvat1** [comment]
I have been also getting 500 for this request, while querying for OpenShift nodes sorted descending by name:
/api/cost-management/v1/reports/openshift/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[node]=*&order_by[node]=desc

**Comment by lcouzens** [comment]
Verified
Commit: f3192e44130ca03e7466302c19cdd9d1dd208246
