### ISSUE TITLE
Openshift query with group_by + order_by on volumes endpoint causing 500 errors

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#837]
**Describe the bug**
Openshift query with group_by + order_by on volumes endpoint causing 500 errors

**To Reproduce**
1. Go to 'api/cost-management/v1/reports/openshift/volumes/?order_by[node]=desc&group_by[node]=*'

```
[2019-04-29 10:07:40,343] INFO: API: /api/cost-management/v1/reports/openshift/volumes/?order_by[node]=desc&group_by[node]=* -- ACCOUNT: 6193296 USER: cost-demo
[2019-04-29 10:07:40,379] INFO: API: /api/cost-management/v1/reports/openshift/volumes/ USER: cost-demo
[2019-04-29 10:07:40,409] ERROR: Internal Server Error: /api/cost-management/v1/reports/openshift/volumes/
Traceback (most recent call last):
 File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
   response = get_response(request)
 File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
   response = self.process_exception_by_middleware(e, request)
 File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/opt/app-root/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
   return view_func(*args, **kwargs)
 File "/opt/app-root/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
   return self.dispatch(request, *args, **kwargs)
 File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
   response = self.handle_exception(exc)
 File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
   self.raise_uncaught_exception(exc)
 File "/opt/app-root/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
   response = handler(request, *args, **kwargs)
 File "/opt/app-root/lib/python3.6/site-packages/rest_framework/decorators.py", line 55, in handler
   return func(*args, **kwargs)
 File "/opt/app-root/src/koku/api/report/ocp/view.py", line 439, in volume
   return _generic_report(request, report='volume', provider='ocp')
 File "/opt/app-root/src/koku/api/report/view.py", line 387, in _generic_report
   output = handler.execute_query()
 File "/opt/app-root/src/koku/api/report/ocp/ocp_query_handler.py", line 166, in execute_query
   query_data = self.order_by(query_data, query_order_by)
 File "/opt/app-root/src/koku/api/report/queries.py", line 1292, in order_by
   reverse=reverse)
 File "/opt/app-root/src/koku/api/report/queries.py", line 1291, in <lambda>
   sorted_data = sorted(sorted_data, key=lambda entry: entry[field].lower(),
AttributeError: 'NoneType' object has no attribute 'lower'
10.129.2.1 - - [29/Apr/2019:10:07:40 +0000] "GET /api/cost-management/v1/reports/openshift/volumes/?order_by[node]=desc&group_by[node]=* HTTP/1.1" 500 27 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"
```

**Expected behavior**
Report should load correctly

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Commit Hash from status endpoint: a97addc51f93ddc1810cf1453fcdc6dc2c4096a2

**Additional context**
Testing on PROD with demo user

**Comment by chambridge** [comment]
This is now working in production based on my testing. Likely fix came from this PR: https://github.com/project-koku/koku/pull/834

**Comment by lcouzens** [comment]
Yeh looks good to me too. Though I noticed it happening locally intermittently yesterday so I will keep an eye out if it pops up again.

Verified
