### ISSUE TITLE
Unable to read root certificate file for RDS databases

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#921]
**Describe the bug**
While running QE tests the following backtrace was seen running against RDS database with SSL.  The server recovered successfully.

Looking at the temporary directory on production there are many temporary PEM files.  It should be investigated why so many root CA cert files are being generated.  While it's not clear how this would lead to a root file not being found it could be a contributing factor.

Backtrace:
```
[2019-06-26 15:03:10,594] INFO: API: /api/cost-management/v1/reports/openshift/costs/?filter[time_scope_units]=month&filter[time_scope_value]=-2&filter[resolution]=daily -- ACCOUNT: 6089719 USER: insights-qa
[2019-06-26 15:03:10,608] INFO: API: /api/cost-management/v1/reports/openshift/volumes/?filter[time_scope_units]=month&filter[time_scope_value]=-2&filter[resolution]=daily -- ACCOUNT: 6089719 USER: insights-qa
[2019-06-26 15:03:10,695] ERROR: Internal Server Error: /api/cost-management/v1/reports/openshift/costs/
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not read root certificate file "/tmp/tmpqzyhj230pem": no SSL error reported


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/app-root/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/opt/app-root/src/koku/koku/middleware.py", line 202, in process_request
    customer = Customer.objects.filter(account_id=account).get()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/opt/app-root/lib/python3.6/site-packages/tenant_schemas/postgresql_backend/base.py", line 118, in _cursor
    cursor = super(DatabaseWrapper, self)._cursor()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not read root certificate file "/tmp/tmpqzyhj230pem": no SSL error reported

10.130.6.1 - - [26/Jun/2019:15:03:10 +0000] "GET /api/cost-management/v1/reports/openshift/costs/?filter[time_scope_units]=month&filter[time_scope_value]=-2&filter[resolution]=daily HTTP/1.1" 500 27 "-" "python-requests/2.21.0"
[2019-06-26 15:03:10,696] ERROR: Internal Server Error: /api/cost-management/v1/reports/openshift/volumes/
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not read root certificate file "/tmp/tmpsakxzhx2pem": no SSL error reported


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/app-root/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/opt/app-root/src/koku/koku/middleware.py", line 202, in process_request
    customer = Customer.objects.filter(account_id=account).get()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/opt/app-root/lib/python3.6/site-packages/tenant_schemas/postgresql_backend/base.py", line 118, in _cursor
    cursor = super(DatabaseWrapper, self)._cursor()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not read root certificate file "/tmp/tmpsakxzhx2pem": no SSL error reported

10.130.6.1 - - [26/Jun/2019:15:03:10 +0000] "GET /api/cost-management/v1/reports/openshift/volumes/?filter[time_scope_units]=month&filter[time_scope_value]=-2&filter[resolution]=daily HTTP/1.1" 500 27 "-" "python-requests/2.21.0"
[2019-06-26 15:03:10 +0000] [191] [INFO] Booting worker with pid: 191
[2019-06-26 15:03:10,792] ERROR: Internal Server Error: /api/cost-management/v1/reports/openshift/costs/
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not read root certificate file "/tmp/tmpktfg0vvnpem": no SSL error reported


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/app-root/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/opt/app-root/src/koku/koku/middleware.py", line 202, in process_request
    customer = Customer.objects.filter(account_id=account).get()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/opt/app-root/lib/python3.6/site-packages/tenant_schemas/postgresql_backend/base.py", line 118, in _cursor
    cursor = super(DatabaseWrapper, self)._cursor()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not read root certificate file "/tmp/tmpktfg0vvnpem": no SSL error reported

10.130.6.1 - - [26/Jun/2019:15:03:10 +0000] "GET /api/cost-management/v1/reports/openshift/costs/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=daily HTTP/1.1" 500 27 "-" "python-requests/2.21.0"
[2019-06-26 15:03:10,794] ERROR: Internal Server Error: /api/cost-management/v1/reports/openshift/compute/
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not read root certificate file "/tmp/tmpnxw_bj7npem": no SSL error reported


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/app-root/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/opt/app-root/src/koku/koku/middleware.py", line 202, in process_request
    customer = Customer.objects.filter(account_id=account).get()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
10.130.6.1 - - [26/Jun/2019:15:03:10 +0000] "GET /api/cost-management/v1/reports/openshift/compute/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&filter[limit]=3&group_by[cluster]=* HTTP/1.1" 500 27 "-" "python-requests/2.21.0"
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/opt/app-root/lib/python3.6/site-packages/tenant_schemas/postgresql_backend/base.py", line 118, in _cursor
    cursor = super(DatabaseWrapper, self)._cursor()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not read root certificate file "/tmp/tmpnxw_bj7npem": no SSL error reported

[2019-06-26 15:03:10,795] ERROR: Internal Server Error: /api/cost-management/v1/reports/openshift/compute/
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not read root certificate file "/tmp/tmpdembzw5lpem": no SSL error reported


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/app-root/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/opt/app-root/src/koku/koku/middleware.py", line 202, in process_request
    customer = Customer.objects.filter(account_id=account).get()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/opt/app-root/lib/python3.6/site-packages/tenant_schemas/postgresql_backend/base.py", line 118, in _cursor
    cursor = super(DatabaseWrapper, self)._cursor()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/app-root/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not read root certificate file "/tmp/tmpdembzw5lpem": no SSL error reported
```

**Expected behavior**
The root certificate should always be accessible.

**Additional context**
PR that enabled SSL: https://github.com/project-koku/koku/pull/818

**Comment by dccurtis** [comment]
@chambridge pointed me to this as something to consider for an alternative way to ingest RDS client certs:
https://docs.openshift.com/container-platform/3.7/dev_guide/projected_volumes.html

**Comment by chambridge** [comment]
https://github.com/project-koku/koku/pull/940

**Comment by lcouzens** [comment]
Verified
commit: "b3e72578a4dd3db91f15953cca6eea729ab652bc"
